<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/uploads/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_ATTACH_FILE' => '附加檔案' ,
   'LBL_ATTACH' => '附加' ,
   'LBL_CANCEL' => '取消' ,
   'LBL_STEP_SELECT_FILE' => '步驟一：選擇檔案' ,
   'LBL_BROWSE_FILES' => '點選瀏覽器按鈕並且選擇要附加的檔案' ,
   'LBL_DESCRIPTION' => '步驟二：填入一些描述' ,
   'LBL_OPTIONAL' => '（選擇性輸入）' );


