<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DocumentRevisions/language/zh-tw.lang.php, 20080423 Thu 24/04/08 00:08:47 
  * Description : 20080423.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '文件版本' ,
   'LNK_NEW_DOCUMENT' => '建立文件' ,
   'LNK_DOCUMENT_LIST' => '文件列表' ,
   'LBL_REVISION_NAME' => '版本編號' ,
   'LBL_FILENAME' => '檔案名稱' ,
   'LBL_MIME' => 'Mime 類型' ,
   'LBL_REVISION' => '版本' ,
   'LBL_DOCUMENT' => '相關文件' ,
   'LBL_LATEST_REVISION' => '最新版本' ,
   'LBL_CHANGE_LOG' => '異動記錄：' ,
   'LBL_ACTIVE_DATE' => '發佈日期' ,
   'LBL_EXPIRATION_DATE' => '到期日' ,
   'LBL_FILE_EXTENSION' => '副檔名' ,
   'LBL_DET_CREATED_BY' => '建立者：' ,
   'LBL_DET_DATE_CREATED' => '建立日期：' ,
   'LBL_DOC_NAME' => '文件名稱：' ,
   'LBL_DOC_VERSION' => '版本：' ,
   'LBL_REV_LIST_REVISION' => '版本' ,
   'LBL_REV_LIST_ENTERED' => '建立日期' ,
   'LBL_REV_LIST_CREATED' => '作者' ,
   'LBL_REV_LIST_LOG' => '異動記錄：' ,
   'LBL_REV_LIST_FILENAME' => '檔案名稱' ,
   'LBL_CURRENT_DOC_VERSION' => '最新版本：' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋文件' ,
   'ERR_FILENAME' => '檔案名稱' ,
   'ERR_DOC_VERSION' => '文件版本' ,
   'ERR_DELETE_CONFIRM' => '您確定要刪除這個文件版本？' ,
   'ERR_DELETE_LATEST_VERSION' => '您沒有刪除這個版本的權限。' ,
   'LNK_NEW_MAIL_MERGE' => '合併郵件' );


