<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CampaignLog/language/zh-tw.lang.php, 20080503 Tue 13/05/08 18:40:34 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_LIST_ID' => '潛在客戶清單編號' ,
   'LBL_ID' => '編號' ,
   'LBL_TARGET_TRACKER_KEY' => '目標客戶追蹤器金鑰' ,
   'LBL_TARGET_ID' => '目標客戶編號' ,
   'LBL_TARGET_TYPE' => '目標客戶類型' ,
   'LBL_ACTIVITY_TYPE' => '活動類型' ,
   'LBL_ACTIVITY_DATE' => '活動日期' ,
   'LBL_RELATED_ID' => '關聯編號' ,
   'LBL_RELATED_TYPE' => '關聯類型' ,
   'LBL_DELETED' => '刪除' ,
   'LBL_MODULE_NAME' => '活動紀錄' ,
   'LBL_LIST_RECIPIENT_EMAIL' => '收件人信箱' ,
   'LBL_LIST_RECIPIENT_NAME' => '收件人名稱' ,
   'LBL_ARCHIVED' => '已保存' ,
   'LBL_HITS' => '點選次數' ,
   'LBL_CAMPAIGN_NAME' => '名稱：' ,
   'LBL_CAMPAIGN' => '活動：' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_INVITEE' => '聯絡人' ,
   'LBL_LIST_CAMPAIGN_NAME' => '活動' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_LIST_TYPE' => '類型' ,
   'LBL_LIST_END_DATE' => '結束日期' ,
   'LBL_DATE_ENTERED' => '輸入日期' ,
   'LBL_DATE_MODIFIED' => '修改日期' ,
   'LBL_MODIFIED' => '修改者: ' ,
   'LBL_CREATED' => '建立者: ' ,
   'LBL_TEAM' => '團隊：' ,
   'LBL_ASSIGNED_TO' => '指派給: ' ,
   'LBL_CAMPAIGN_START_DATE' => '開始日期：' ,
   'LBL_CAMPAIGN_END_DATE' => '結束日期：' ,
   'LBL_CAMPAIGN_STATUS' => '狀態：' ,
   'LBL_CAMPAIGN_BUDGET' => '預算：' ,
   'LBL_CAMPAIGN_EXPECTED_COST' => '預期成本：' ,
   'LBL_CAMPAIGN_ACTUAL_COST' => '實際成本：' ,
   'LBL_CAMPAIGN_EXPECTED_REVENUE' => '預期收入：' ,
   'LBL_CAMPAIGN_TYPE' => '類型：' ,
   'LBL_CAMPAIGN_OBJECTIVE' => '目的：' ,
   'LBL_CAMPAIGN_CONTENT' => '說明：' ,
   'LBL_LIST_FORM_TITLE' => '達到目標的活動' ,
   'LBL_LIST_ACTIVITY_DATE' => '活動日期' ,
   'LBL_LIST_CAMPAIGN_OBJECTIVE' => '活動目的' ,
   'LBL_RELATED' => '關聯' ,
   'LBL_CLICKED_URL_KEY' => '已點閱網址鍵值' ,
   'LBL_URL_CLICKED' => '已點閱網址' ,
   'LBL_MORE_INFO' => '更多資訊' );


