<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Campaigns/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_CAMPAIGN_INFORMATION' => '活動資訊' ,
   'LBL_CUSTOM_INFORMATION' => '自訂資訊' ,
   'LBL_DESCRIPTION_INFORMATION' => '描述資訊' ,
   'LBL_EXPECTATIONS_AND_ACTUALS' => '預估與實際' ,
   'Campaign Name' => '活動名稱' ,
   'Campaign Type' => '活動類型' ,
   'Campaign Status' => '活動狀態' ,
   'Campaign ID' => '活動編號' ,
   'Expected Close Date' => '預期結束日期' ,
   'Expected Revenue' => '預期收益' ,
   'Budget Cost' => '預算' ,
   'Actual Cost' => '實際成本' ,
   'Expected Response' => '預期回應' ,
   'Assigned To' => '任務指派' ,
   'Num Sent' => '寄發數量' ,
   'Created Time' => '建立時間' ,
   'Modified Time' => '修改時間' ,
   'Description' => '描述' ,
   'Product' => '產品' ,
   'Target Audience' => '目標族群' ,
   'TargetSize' => '目標規模' ,
   'Sponsor' => '贊助商' ,
   'Expected Sales Count' => '預期銷售量' ,
   'Expected Response Count' => '預期回應量' ,
   'Expected ROI' => '預期收益' ,
   'Actual Sales Count' => '實際銷售量' ,
   'Actual Response Count' => '實際回應量' ,
   'Actual ROI' => '實際收益' ,
   'Select One' => '選擇一個' ,
   'LBL_LOAD_LIST' => '讀取清單' ,
   'Conference' => '研討會' ,
   'Webinar' => '網路發表會' ,
   'Trade Show' => '貿易展覽' ,
   'Public Relations' => '公開關係' ,
   'Partners' => '夥伴' ,
   'Referral Program' => '介紹活動' ,
   'Advertisement' => '廣告' ,
   'Banner Ads' => '網站廣告' ,
   'Direct Mail' => '直接發信' ,
   'Email' => '電子郵件' ,
   'Telemarketing' => '電話行銷' ,
   'Others' => '其他' ,
   'Planning' => '規劃中' ,
   'Active' => '啟用' ,
   'Inactive' => '停用' ,
   'Complete' => '完成' ,
   'Cancelled' => '取消日期' ,
   'Excellent' => '極佳' ,
   'Good' => '好' ,
   'Average' => '平均' ,
   'Poor' => '差' );


