<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Feeds/language/zh-tw.lang.php, 20080513 Tue 20/05/08 22:11:08 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '新聞' ,
   'LBL_MODULE_ID' => '潛在客戶' ,
   'LBL_MODULE_TITLE' => '新聞：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => 'RSS新聞來源搜尋' ,
   'LBL_LIST_FORM_TITLE' => 'RSS新聞來源清單' ,
   'LBL_MY_LIST_FORM_TITLE' => '我的RSS新聞來源清單' ,
   'LBL_NEW_FORM_TITLE' => '新增RSS新聞來源' ,
   'NTC_DELETE_CONFIRMATION' => '確定要刪除這個記錄嗎?' ,
   'ERR_DELETE_RECORD' => '欲刪除聯絡人記錄，必須有相應的記錄編號.' ,
   'LNK_NEW_FEED' => '新增RSS新聞來源' ,
   'LNK_FEED_LIST' => '所有RSS新聞來源' ,
   'LNK_MY_FEED_LIST' => '我的RSS新聞來源清單' ,
   'LBL_TITLE' => '標題' ,
   'LBL_RSS_URL' => 'RSS網址' ,
   'LBL_ONLY_MY' => '只顯示我的最愛' ,
   'LBL_VISIT_WEBSITE' => '訪問網站' ,
   'LBL_LAST_UPDATED' => '最後更新' ,
   'LBL_DELETE_FAVORITES' => '從我的最愛刪除' ,
   'LBL_DELETE_FAV_BUTTON_TITLE' => '從我的最愛刪除 [Alt+D]' ,
   'LBL_DELETE_FAV_BUTTON_KEY' => '[Alt+D]' ,
   'LBL_DELETE_FAV_BUTTON_LABEL' => '從我的最愛刪除' ,
   'LBL_ADD_FAV_BUTTON_TITLE' => '新增到我的最愛 [Alt+A]' ,
   'LBL_ADD_FAV_BUTTON_KEY' => '[Alt+A]' ,
   'LBL_ADD_FAV_BUTTON_LABEL' => '新增到我的最愛' ,
   'LBL_MOVE_UP' => '上移' ,
   'LBL_MOVE_DOWN' => '下移' ,
   'LBL_FEED_NOT_AVAILABLE' => '來源不存在' ,
   'LBL_REFRESH_CACHE' => '點選這裡更新快取' ,
   'LBL_TILE' => '標題' ,
   'LBL_URL' => '網址' ,
   'LBL_DESCRIPTION' => '說明' );


