<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DynamicFields/language/zh-tw.lang.php, 20080513 Tue 13/05/08 22:33:01 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_EMAIL' => '保留信件' ,
   'LNK_CALL_LIST' => '電話' ,
   'LNK_MEETING_LIST' => '會議' ,
   'LNK_TASK_LIST' => '任務' ,
   'LNK_NOTE_LIST' => '備註' ,
   'LNK_EMAIL_LIST' => '電子郵件' );


