<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/file/language/application/zh-tw.lang.php, 20080513 Mon 16/06/08 21:46:20 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_category_dom' => array (
      '' => '' ,
      'Marketing' => '行銷' ,
      'Knowledege Base' => '知識庫' ,
      'Sales' => '銷售'   ),
   '_status_dom' => array (
      'Active' => '有效' ,
      'Draft' => '草稿' ,
      'FAQ' => '常見問答' ,
      'Expired' => '已過期' ,
      'Under Review' => '檢閱中' ,
      'Pending' => 'Pending'   ),
   '_subcategory_dom' => array (
      '' => '' ,
      'Marketing Collateral' => '併行市場行銷' ,
      'Product Brochures' => '產品說明' ,
      'FAQ' => '常見問答'   ));


