<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/iFrames/language/zh-tw.lang.php, 1 Mon 03/03/08 16:17:38 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '網站' ,
   'LBL_MODULE_ID' => 'iFrames' ,
   'LBL_MODULE_TITLE' => '網站：首頁' ,
   'LBL_LIST_STATUS' => '顯示' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_URL' => '網站' ,
   'LBL_LIST_TYPE' => '類型' ,
   'LBL_LIST_CREATED_BY' => '作者' ,
   'LBL_LIST_PLACEMENT' => '位置' ,
   'LBL_LIST_FORM_TITLE' => '網站清單' ,
   'LBL_ADD_SITE' => '新增網站' ,
   'LBL_LIST_SITES' => '列出網站' ,
   'LBL_ID' => '編號' ,
   'LBL_CHECKED' => '已勾選' ,
   'DEFAULT_URL' => 'http://twpug.net/modules/newbb/viewforum.php?forum=25' ,
   'all' => '標籤選單與快速鍵選單' ,
   'tab' => '標籤選單' ,
   'shortcut' => '快速鍵選單' ,
   'personal' => '個人' ,
   'global' => '共用' );


