<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/LabelEditor/language/zh-tw.lang.php, 20080513 Wed 14/05/08 22:37:54 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '標籤編輯器' ,
   'LBL_KEY' => '索引：' ,
   'LBL_VALUE' => '數值：' );


