<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/issue/language/application/zh-tw.lang.php, 20080513 Tue 13/05/08 22:33:01 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_priority_dom' => array (
      'P1' => '高' ,
      'P2' => 'Medium' ,
      'P3' => '低'   ),
   '_resolution_dom' => array (
      '' => '' ,
      'Accepted' => '已收到' ,
      'Duplicate' => '複製' ,
      'Closed' => '結束' ,
      'Out of Date' => '過期' ,
      'Invalid' => '錯誤'   ),
   '_status_dom' => array (
      'New' => 'New' ,
      'Assigned' => '已指派' ,
      'Closed' => '結束' ,
      'Pending Input' => '等待輸入' ,
      'Rejected' => '拒絕' ,
      'Duplicate' => '複製'   ),
   '_type_dom' => array (
      'Administration' => '管理' ,
      'Product' => '產品' ,
      'User' => '分配給：'   ));


