<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProspectLists/language/zh-tw.lang.php, 20080423 Thu 24/04/08 00:08:47 
  * Description : 20080423.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '目標客戶列表' ,
   'LBL_MODULE_ID' => '目標客戶列表' ,
   'LBL_MODULE_TITLE' => '目標客戶列表：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋目標客戶列表' ,
   'LBL_LIST_FORM_TITLE' => '目標列表' ,
   'LBL_PROSPECT_LIST_NAME' => '名稱' ,
   'LBL_NAME' => '名稱' ,
   'LBL_ENTRIES' => '總數：' ,
   'LBL_LIST_PROSPECT_LIST_NAME' => '潛在客戶列表' ,
   'LBL_LIST_ENTRIES' => '列表中的目標客戶' ,
   'LBL_LIST_DESCRIPTION' => '說明' ,
   'LBL_LIST_TYPE_NO' => '類型' ,
   'LBL_LIST_END_DATE' => '結束日期' ,
   'LBL_DATE_ENTERED' => '輸入日期' ,
   'LBL_DATE_MODIFIED' => '修改日期' ,
   'LBL_MODIFIED' => '修改者' ,
   'LBL_CREATED' => '作者' ,
   'LBL_TEAM' => '團隊' ,
   'LBL_ASSIGNED_TO' => '指派給' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LNK_NEW_CAMPAIGN' => '建立活動' ,
   'LNK_CAMPAIGN_LIST' => '活動' ,
   'LNK_NEW_PROSPECT_LIST' => '建立潛在客戶列表' ,
   'LNK_PROSPECT_LIST_LIST' => '目標列表' ,
   'LBL_MODIFIED_BY' => '修改者' ,
   'LBL_CREATED_BY' => '作者' ,
   'LBL_DATE_CREATED' => '建立日期：' ,
   'LBL_DATE_LAST_MODIFIED' => '修改日期：' ,
   'LNK_NEW_PROSPECT' => '建立潛在客戶' ,
   'LNK_PROSPECT_LIST' => '潛在客戶' ,
   'LBL_PROSPECT_LISTS_SUBPANEL_TITLE' => '目標列表' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => '聯絡人' ,
   'LBL_LEADS_SUBPANEL_TITLE' => '準客戶' ,
   'LBL_PROSPECTS_SUBPANEL_TITLE' => '潛在客戶' ,
   'LBL_COPY_PREFIX' => '副本於' ,
   'LBL_USERS_SUBPANEL_TITLE' => '使用者' ,
   'LBL_TYPE' => '類型' ,
   'LBL_LIST_TYPE' => '類型' ,
   'LBL_LIST_TYPE_LIST_NAME' => '類型' ,
   'LBL_NEW_FORM_TITLE' => '新目標客戶列表' ,
   'LBL_MARKETING_MESSAGE' => '電子郵件市場訊息' ,
   'LBL_DOMAIN_NAME' => '網域名稱' ,
   'LBL_DOMAIN' => '這個網域名稱沒有信箱：' ,
   'LBL_LIST_PROSPECTLIST_NAME' => '名稱' );


