<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Releases/language/zh-tw.lang.php,  Wed 20/02/08 14:57:08 
  * Description : .
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '版本' ,
   'LBL_MODULE_TITLE' => '產品：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋產品' ,
   'LBL_LIST_FORM_TITLE' => '產品清單' ,
   'LBL_NEW_FORM_TITLE' => '新產品' ,
   'LBL_RELEASE' => '版本：' ,
   'LBL_LIST_NAME' => '版本' ,
   'LBL_NAME' => '產品版本：' ,
   'LBL_LIST_LIST_ORDER' => '訂單' ,
   'LBL_LIST_ORDER' => '順序：' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_STATUS' => '狀態：' ,
   'LNK_NEW_RELEASE' => '產品清單' ,
   'NTC_DELETE_CONFIRMATION' => '確定要刪除這個記錄嗎?' ,
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除' ,
   'NTC_STATUS' => '設定狀態為停售中，產品清單就會移除這個項目' ,
   'NTC_LIST_ORDER' => '設定產品在清單中的顯示順序' ,
   'release_status_dom' => array (
      'Active' => '有效' ,
      'Inactive' => '無效'   ));


