<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/LabelEditor/language/zh-tw.lang.php, 1 Mon 03/03/08 16:17:38 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '標籤編輯器' ,
   'LBL_KEY' => '索引：' ,
   'LBL_VALUE' => '數值：' );


