<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/System/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_SYSTEM_CONFIG' => '系統環境設定' );


