<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Help/language/zh-tw.lang.php, 1 Sat 16/02/08 08:01:39 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '公司' ,
   'LBL_MODULE_TITLE' => '客戶：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋客戶' ,
   'LBL_LIST_FORM_TITLE' => '客戶列表' ,
   'LBL_NEW_FORM_TITLE' => '新增客戶' ,
   'LNK_NEW_CONTACT' => '建立聯絡人' ,
   'LNK_NEW_ACCOUNT' => '新增客戶' ,
   'LNK_NEW_OPPORTUNITY' => '建立機會' ,
   'LNK_NEW_CASE' => '建立案件' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_EMAIL' => '保留信件' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除公司.' );


