<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailMarketing/language/zh-tw.lang.php, 1 Sat 16/02/08 06:32:44 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_REPLY_ADDR' => '回覆信箱：' ,
   'LBL_REPLY_NAME' => '回覆名稱：' ,
   'LBL_MODULE_NAME' => '電子郵件行銷' ,
   'LBL_MODULE_TITLE' => '郵件行銷：首頁' ,
   'LBL_LIST_FORM_TITLE' => '郵件行銷活動' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_FROM_ADDR' => '寄件人信箱' ,
   'LBL_LIST_DATE_START' => '開始日期' ,
   'LBL_LIST_TEMPLATE_NAME' => '郵件樣板' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_STATUS' => '狀態' ,
   'LBL_STATUS_TEXT' => '狀態：' ,
   'LBL_TEMPLATE_NAME' => '樣板名稱' ,
   'LBL_DATE_ENTERED' => '輸入日期' ,
   'LBL_DATE_MODIFIED' => '修改日期' ,
   'LBL_MODIFIED' => '修改者：' ,
   'LBL_CREATED' => '建立者：' ,
   'LBL_MESSAGE_FOR' => '寄送這封信給：' ,
   'LBL_MESSAGE_FOR_ID' => '信件於' ,
   'LBL_FROM_NAME' => '寄件人名稱：' ,
   'LBL_FROM_ADDR' => '寄件人信箱：' ,
   'LBL_DATE_START' => '開始日期' ,
   'LBL_TIME_START' => '開始時間' ,
   'LBL_START_DATE_TIME' => '開始日期與時間：' ,
   'LBL_TEMPLATE' => '郵件樣板：' ,
   'LBL_MODIFIED_BY' => '修改者：' ,
   'LBL_CREATED_BY' => '建立者：' ,
   'LBL_DATE_CREATED' => '建立日期：' ,
   'LBL_DATE_LAST_MODIFIED' => '修改日期：' ,
   'LNK_NEW_CAMPAIGN' => '建立活動' ,
   'LNK_CAMPAIGN_LIST' => '活動' ,
   'LNK_NEW_PROSPECT_LIST' => '建立潛在客戶列表' ,
   'LNK_PROSPECT_LIST_LIST' => '目標列表' ,
   'LNK_NEW_PROSPECT' => '建立潛在客戶' ,
   'LNK_PROSPECT_LIST' => '潛在客戶' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '電子郵件行銷' ,
   'LBL_CREATE_EMAIL_TEMPLATE' => '建立' ,
   'LBL_EDIT_EMAIL_TEMPLATE' => '編輯' ,
   'LBL_FROM_MAILBOX' => '寄件人信箱' ,
   'LBL_FROM_MAILBOX_NAME' => '使用信箱：' ,
   'LBL_PROSPECT_LIST_SUBPANEL_TITLE' => '目標列表' ,
   'LBL_ALL_PROSPECT_LISTS' => '活動中的所有目標清單。' ,
   'LBL_RELATED_PROSPECT_LISTS' => '與這封郵件有關的目標清單。' ,
   'LBL_PROSPECT_LIST_NAME' => '目標清單名稱' ,
   'LBL_LIST_PROSPECT_LIST_NAME' => '目標清單' ,
   'LBL_MODULE_SEND_TEST' => '活動：寄送測試' ,
   'LBL_MODULE_SEND_EMAILS' => '活動：寄送郵件' ,
   'LBL_SCHEDULE_MESSAGE_TEST' => '請選擇希望寄出的活動訊息' ,
   'LBL_SCHEDULE_MESSAGE_EMAILS' => '請選擇希望寄送活動訊息的開始日期與時間：' ,
   'LBL_SCHEDULE_BUTTON_TITLE' => '寄送' ,
   'LBL_SCHEDULE_BUTTON_LABEL' => '寄送' ,
   'LBL_SCHEDULE_BUTTON_KEY' => 'T' );


