<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Rss/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '新聞' ,
   'LBL_MODULE_TITLE' => '新聞：首頁' ,
   'LBL_NEW_RSS_ENTRY' => '新聞RSS資料來源網址：' ,
   'LBL_SEARCH_RSS' => '標題搜尋：' ,
   'LBL_NEW_RSS_BUTTON' => '新增' ,
   'LBL_STARRED_RSS' => '重要新聞' ,
   'LBL_POP_CRM_RSS' => 'CRM相關熱門新聞' ,
   'LBL_ALL_RSS_FEEDS' => '所有他站新聞' ,
   'LBL_VTIGER_RSS_READER' => 'vtiger RSS 閱讀器' ,
   'LBL_MORE' => '更多...' ,
   'LBL_SUBJECT' => '標題' ,
   'LBL_SENDER' => '寄件人' ,
   'LBL_CATEGORY' => '類別：' ,
   'LBL_FEED' => '資料來源：' ,
   'LBL_FEED_SOURCES' => '資料來源' ,
   'LBL_ADD_RSS_FEED' => '新增 RSS 資料來源' ,
   'LBL_DELETE_BUTTON' => '刪除' ,
   'LBL_SET_DEFAULT_BUTTON' => '設為預設' ,
   'LBL_FEEDS_LIST' => '資料來源：' ,
   'LBL_ERROR_MSG' => '沒有選擇 RSS 來源或是您的代理伺服器設定有問題' ,
   'LBL_REGRET_MSG' => '抱歉：無法取得 RSS 網址' ,
   'UNABLE_TO_SAVE' => '無法儲存 RSS 來源網址' ,
   'NOT_A_VALID' => 'RSS 來源網址有誤' );


