<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Notes/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '記事' ,
   'LBL_MODULE_TITLE' => '記事： 首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋記事' ,
   'LBL_LIST_FORM_TITLE' => '記事列表' ,
   'LBL_NEW_FORM_TITLE' => '新增備忘錄' ,
   'LBL_LIST_SUBJECT' => '標題' ,
   'LBL_LIST_CONTACT_NAME' => '聯絡人名稱' ,
   'LBL_LIST_RELATED_TO' => '相關人員' ,
   'LBL_LIST_DATE_MODIFIED' => '修改時間' ,
   'LBL_NOTE' => '摘要' ,
   'LBL_NOTE_SUBJECT' => '記事標題：' ,
   'LBL_CONTACT_NAME' => '聯絡人名稱：' ,
   'LBL_PHONE' => '電話：' ,
   'LBL_SUBJECT' => '標題：' ,
   'LBL_CLOSE' => '關閉：' ,
   'LBL_RELATED_TO' => '相關人事：' ,
   'LBL_EMAIL_ADDRESS' => '電子郵件地址：' ,
   'LBL_COLON' => '：' ,
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除客戶資料。' ,
   'LBL_LIST_FILENAME' => '檔案' ,
   'LBL_FILENAME' => '附件：' ,
   'LBL_NOTE_INFORMATION' => '記事資訊' ,
   'LBL_TOOL_FORM_TITLE' => '記事編輯器' ,
   'Contact Name' => '聯絡人名稱' ,
   'Related To' => '相關人事' ,
   'Subject' => '標題' ,
   'Created Time' => '建立時間' ,
   'Modified Time' => '修改時間' ,
   'Attachment' => '附加檔案' ,
   'Note' => '記事' ,
   'Related to' => '相關人事' ,
   'Last Modified' => '修改時間' ,
   'File' => '檔案' ,
   'LBL_ALL' => '全選' ,
   'Title' => '標題' );


