<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/file/language/zh-tw.lang.php, 20080513 Wed 14/05/08 22:37:54 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '文件' ,
   'LBL_MODULE_TITLE' => '文件：首頁' ,
   'LNK_NEW_DOCUMENT' => '建立文件' ,
   'LNK_DOCUMENT_LIST' => '文件列表' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋文件' ,
   'LBL_DOCUMENT_ID' => '文件編號' ,
   'LBL_NAME' => '文件名稱' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LBL_CATEGORY' => '類別' ,
   'LBL_SUBCATEGORY' => '子類別' ,
   'LBL_STATUS' => '狀態' ,
   'LBL_IS_TEMPLATE' => '這是樣板' ,
   'LBL_TEMPLATE_TYPE' => '文件類型' ,
   'LBL_REVISION_NAME' => '版本編號' ,
   'LBL_MIME' => 'Mime 類型' ,
   'LBL_REVISION' => '版本' ,
   'LBL_DOCUMENT' => '相關文件' ,
   'LBL_LATEST_REVISION' => '最新版本' ,
   'LBL_CHANGE_LOG' => '異動記錄：' ,
   'LBL_ACTIVE_DATE' => '發佈日期' ,
   'LBL_EXPIRATION_DATE' => '到期日' ,
   'LBL_FILE_EXTENSION' => '副檔名' ,
   'LBL_CAT_OR_SUBCAT_UNSPEC' => '未指定' ,
   'LBL_NEW_FORM_TITLE' => '新增文件' ,
   'LBL_DOC_NAME' => '文件名稱：' ,
   'LBL_FILENAME' => '檔案名稱：' ,
   'LBL_DOC_VERSION' => '版本：' ,
   'LBL_CATEGORY_VALUE' => '產品類別' ,
   'LBL_SUBCATEGORY_VALUE' => '子類別：' ,
   'LBL_DOC_STATUS' => '狀態：' ,
   'LBL_DET_TEMPLATE_TYPE' => '文件類型：' ,
   'LBL_DOC_DESCRIPTION' => '描述：' ,
   'LBL_DOC_ACTIVE_DATE' => '發佈日期：' ,
   'LBL_DOC_EXP_DATE' => '到期日：' ,
   'LBL_LIST_FORM_TITLE' => '文件列表' ,
   'LBL_LIST_DOCUMENT' => '文件' ,
   'LBL_LIST_CATEGORY' => '類別' ,
   'LBL_LIST_SUBCATEGORY' => '子類別' ,
   'LBL_LIST_REVISION' => '版本' ,
   'LBL_LIST_LAST_REV_CREATOR' => '發佈者' ,
   'LBL_LIST_LAST_REV_DATE' => '版本日期' ,
   'LBL_LIST_VIEW_DOCUMENT' => '檢視' ,
   'LBL_LIST_DOWNLOAD' => '下載' ,
   'LBL_LIST_ACTIVE_DATE' => '發佈日期' ,
   'LBL_LIST_EXP_DATE' => '到期日' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_SF_DOCUMENT' => '文件名稱：' ,
   'LBL_SF_CATEGORY' => '產品類別' ,
   'LBL_SF_SUBCATEGORY' => '子類別：' ,
   'LBL_SF_ACTIVE_DATE' => '發佈日期：' ,
   'LBL_SF_EXP_DATE' => '到期日：' ,
   'DEF_CREATE_LOG' => '文件建立' ,
   'ERR_DOC_NAME' => '文件名稱' ,
   'ERR_DOC_ACTIVE_DATE' => '發佈日期' ,
   'ERR_DOC_EXP_DATE' => '到期日' ,
   'ERR_FILENAME' => '檔案名稱' ,
   'LBL_TREE_TITLE' => '文件' ,
   'LBL_LIST_DOCUMENT_NAME' => '文件名稱' );


