<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACLActions/language/zh-tw.lang.php, 20080513 Sun 18/05/08 10:13:48 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ACCESS_ALL' => '全部' ,
   'LBL_ACCESS_NONE' => '無' ,
   'LBL_ACCESS_OWNER' => '擁有者' ,
   'LBL_ACCESS_NORMAL' => '一般' ,
   'LBL_ACCESS_ADMIN' => '系統管理' ,
   'LBL_ACCESS_ENABLED' => '啟用' ,
   'LBL_ACCESS_DISABLED' => '停用' ,
   'LBL_NAME' => '名稱' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LIST_ROLES' => '角色列表' ,
   'LBL_USERS_SUBPANEL_TITLE' => '使用者' ,
   'LIST_ROLES_BY_USER' => '依使用者列出角色' ,
   'LBL_ROLES_SUBPANEL_TITLE' => '使用者角色' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋' ,
   'LBL_ACTION_VIEW' => '檢視' ,
   'LBL_ACTION_EDIT' => '編輯' ,
   'LBL_ACTION_DELETE' => '刪除' ,
   'LBL_ACTION_IMPORT' => '匯入' ,
   'LBL_ACTION_EXPORT' => '匯出' ,
   'LBL_ACTION_LIST' => '列表' ,
   'LBL_ACTION_ACCESS' => '存取權限' ,
   'LBL_ACTION_ADMIN' => '使用者類型' ,
   'LBL_ACCESS_DEFAULT' => '預設' );


