<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/issue/language/zh-tw.lang.php, 1 Tue 19/02/08 16:08:34 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_NAME' => '名稱' ,
   'LBL_NUMBER' => '數字：' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_RESOLUTION' => '分析' ,
   'LBL_LAST_MODIFIED' => '最新修改' ,
   'LBL_ASSIGNED_TO_ID' => '指派給：' ,
   'LBL_ASSIGNED_TO_NAME' => '指派給：' ,
   'LBL_WORK_LOG' => '工作記錄' ,
   'LBL_CREATED_BY' => '建立者：' ,
   'LBL_DATE_CREATED' => '建立日期:' ,
   'LBL_DATE_ENTERED' => '建立日期:' ,
   'LBL_DATE_MODIFIED' => '修改日期:' ,
   'LBL_MODIFIED_BY' => '最後更新者：' ,
   'LBL_ASSIGNED_USER' => '指派的使用者：' ,
   'LBL_SYSTEM_ID' => '系統編號:' ,
   'LBL_TEAM_NAME' => '團隊名稱:' ,
   'LBL_TYPE' => '類型：' );


