<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/PriceBooks/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_PRICEBOOK_INFORMATION' => '價目表資訊：' ,
   'LBL_CUSTOM_INFORMATION' => '自訂資訊' ,
   'LBL_DESCRIPTION_INFORMATION' => '描述名稱：' ,
   'Price Book Name' => '價目表名稱' ,
   'Product Name' => '商品名稱' ,
   'Active' => '啟用' ,
   'Description' => '描述' ,
   'Created Time' => '建立時間' ,
   'Modified Time' => '修改時間' ,
   'LBL_LIST_PRODUCT_NAME' => '商品名稱' ,
   'LBL_PRODUCT_CODE' => '零件編號' ,
   'LBL_PRODUCT_UNIT_PRICE' => '單價' ,
   'LBL_PB_LIST_PRICE' => '定價' ,
   'LBL_ACTION' => '行動' ,
   'PriceBook' => '價目表' );


