<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CampaignTrackers/language/zh-tw.lang.php, 1 Sat 16/02/08 06:48:36 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => '編號' ,
   'LBL_TRACKER_KEY' => '追蹤鍵值' ,
   'LBL_TRACKER_URL' => '追蹤網址' ,
   'LBL_TRACKER_NAME' => '追蹤名稱' ,
   'LBL_CAMPAIGN_ID' => '活動編號' ,
   'LBL_DATE_ENTERED' => '輸入日期' ,
   'LBL_DATE_MODIFIED' => '修改日期' ,
   'LBL_MODIFIED_USER_ID' => '修改者編號' ,
   'LBL_CREATED_BY' => '建立者' ,
   'LBL_DELETED' => '刪除' ,
   'LBL_CAMPAIGN' => '活動' ,
   'LBL_OPTOUT' => '拒絕郵件打擾' ,
   'LBL_MODULE_NAME' => '活動追蹤' ,
   'LBL_EDIT_CAMPAIGN_NAME' => '活動名稱：' ,
   'LBL_EDIT_TRACKER_NAME' => '追蹤名稱：' ,
   'LBL_EDIT_TRACKER_URL' => '追蹤網址：' ,
   'LBL_SUBPANEL_TRACKER_NAME' => '名稱' ,
   'LBL_SUBPANEL_TRACKER_URL' => '網址' ,
   'LBL_SUBPANEL_TRACKER_KEY' => '鍵值' ,
   'LBL_EDIT_MESSAGE_URL' => '活動訊息網址：' ,
   'LBL_EDIT_TRACKER_KEY' => '追蹤鍵值：' ,
   'LBL_EDIT_OPT_OUT' => '拒絕打擾連結？' ,
   'LNK_CAMPAIGN_LIST' => '活動' );


