<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACL/language/zh-tw.lang.php, 20080513 Tue 13/05/08 22:33:01 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ALLOW_ALL' => '全部' ,
   'LBL_ALLOW_NONE' => '無' ,
   'LBL_ALLOW_OWNER' => '擁有者' ,
   'LBL_ROLE' => '角色' ,
   'LBL_NAME' => '名稱' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LIST_ROLES' => '角色列表' ,
   'LBL_USERS_SUBPANEL_TITLE' => '使用者' ,
   'LIST_ROLES_BY_USER' => '依使用者列出角色' ,
   'LBL_ROLES_SUBPANEL_TITLE' => '使用者角色' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋' ,
   'LBL_NO_ACCESS' => '您沒有權限存取這個區域，如果是管理者忘了授權給您，請聯繫您的管理者。' ,
   'LBL_ADDING' => '新增於 ' );


