<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailTemplates/language/zh-tw.lang.php, 1 Sat 01/03/08 17:30:27 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ADD_ANOTHER_FILE' => '新增另一個檔案' ,
   'LBL_ADD_DOCUMENT' => '從系統新增文件' ,
   'LBL_ADD_FILE' => '新增檔案' ,
   'LBL_ATTACHMENTS' => '附加檔案' ,
   'LBL_BODY' => '內容：' ,
   'LBL_CLOSE' => '關閉：' ,
   'LBL_COLON' => '：' ,
   'LBL_CONTACT_AND_OTHERS' => '聯絡人/準客戶/潛在客戶' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_EDIT_ALT_TEXT' => '編輯替代文字' ,
   'LBL_EMAIL_ATTACHMENT' => '郵件附加檔案' ,
   'LBL_HTML_BODY' => 'HTML 內容' ,
   'LBL_INSERT_VARIABLE' => '插入變數：' ,
   'LBL_INSERT_URL_REF' => '插入參考網址' ,
   'LBL_INSERT_TRACKER_URL' => '插入追蹤網址：' ,
   'LBL_INSERT' => '插入' ,
   'LBL_LIST_DATE_MODIFIED' => '最新修改' ,
   'LBL_LIST_DESCRIPTION' => '說明' ,
   'LBL_LIST_FORM_TITLE' => '郵件樣板清單' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_MODULE_NAME' => '電子郵件模版' ,
   'LBL_MODULE_TITLE' => '郵件樣板：首頁' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_NEW_FORM_TITLE' => '建立郵件樣板' ,
   'LBL_PUBLISH' => '發佈：' ,
   'LBL_RELATED_TO' => '相關：' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋郵件樣板' ,
   'LBL_SHOW_ALT_TEXT' => '顯示替代文字' ,
   'LBL_SUBJECT' => '主旨：' ,
   'LBL_SUGAR_DOCUMENT' => 'Sugar 文件' ,
   'LBL_TEAM' => '團隊：' ,
   'LBL_TEAMS_LINK' => '團隊' ,
   'LBL_TEXT_BODY' => '文字內容' ,
   'LBL_USERS' => '使用者' ,
   'LNK_ALL_EMAIL_LIST' => '電子郵件' ,
   'LNK_ARCHIVED_EMAIL_LIST' => '儲存的郵件' ,
   'LNK_CHECK_EMAIL' => '檢查郵件' ,
   'LNK_DRAFTS_EMAIL_LIST' => '草稿' ,
   'LNK_EMAIL_TEMPLATE_LIST' => '電子郵件模版' ,
   'LNK_IMPORT_NOTES' => '匯入記事' ,
   'LNK_NEW_ARCHIVE_EMAIL' => '新增電子郵件' ,
   'LNK_NEW_EMAIL_TEMPLATE' => '建立郵件樣板' ,
   'LNK_NEW_EMAIL' => '保留信件' ,
   'LNK_NEW_SEND_EMAIL' => '新增郵件' ,
   'LNK_SENT_EMAIL_LIST' => '寄件備份' ,
   'LNK_VIEW_CALENDAR' => '今天' ,
   'LBL_NEW' => 'New' ,
   'LNK_CHECK_MY_INBOX' => '檢查我的信件' ,
   'LNK_GROUP_INBOX' => '群組收件匣' ,
   'LNK_MY_ARCHIVED_LIST' => '我的保留信件' ,
   'LNK_MY_DRAFTS' => '我的草稿' ,
   'LNK_MY_INBOX' => '我的收件匣' ,
   'LBL_TEXT_ONLY' => '只有純文字' ,
   'LBL_SEND_AS_TEXT' => '只寄送純文字' ,
   'LBL_ACCOUNT' => '公司' ,
   'LBL_BASE_MODULE' => '基礎模組' ,
   'LBL_FROM_NAME' => '寄件人名稱' ,
   'LBL_PLAIN_TEXT' => '純文字' ,
   'LBL_CREATED_BY' => '建立者' ,
   'LBL_FROM_ADDRESS' => '寄件人信箱' ,
   'LBL_PUBLISHED' => '已發佈' );


