<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Audit/language/zh-tw.lang.php, 20080503 Sat 03/05/08 10:18:53 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_FIELD_NAME' => '欄位' ,
   'LBL_OLD_NAME' => '舊值' ,
   'LBL_NEW_VALUE' => '新值' ,
   'LBL_CREATED_BY' => '修改者' ,
   'LBL_LIST_DATE' => '修改日期' ,
   'LBL_AUDITED_FIELDS' => '這個模組被稽核的欄位：' ,
   'LBL_NO_AUDITED_FIELDS_TEXT' => '這個模組沒有被稽核的欄位' );


