<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EditCustomFields/language/zh-tw.lang.php, 20080513 Wed 14/05/08 22:37:54 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '編輯自訂欄位' ,
   'LBL_ADD_FIELD' => '新增欄位：' ,
   'LBL_MODULE_TITLE' => '編輯自訂欄位' ,
   'LBL_MODULE_SELECT' => '要編輯的模組' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋模組' ,
   'COLUMN_TITLE_NAME' => '欄位名稱' ,
   'COLUMN_TITLE_DISPLAY_LABEL' => '顯示標籤' ,
   'COLUMN_TITLE_LABEL' => '欄位標籤' ,
   'COLUMN_TITLE_DATA_TYPE' => '資料類型' ,
   'COLUMN_TITLE_MAX_SIZE' => '資料上限' ,
   'COLUMN_TITLE_HELP_TEXT' => '說明文字' ,
   'COLUMN_TITLE_COMMENT_TEXT' => '意見文字' ,
   'COLUMN_TITLE_REQUIRED_OPTION' => '必要欄位' ,
   'COLUMN_TITLE_DEFAULT_VALUE' => '預設值' ,
   'COLUMN_TITLE_DEFAULT_EMAIL' => '預設值' ,
   'COLUMN_TITLE_EXT1' => '其他變換欄位 1' ,
   'COLUMN_TITLE_EXT2' => '其他變換欄位 2' ,
   'COLUMN_TITLE_EXT3' => '其他變換欄位 3' ,
   'COLUMN_TITLE_HTML_CONTENT' => 'HTML' ,
   'COLUMN_TITLE_URL' => '預設網址' ,
   'COLUMN_TITLE_AUDIT' => '確定？' ,
   'COLUMN_TITLE_REPORTABLE' => '可用在報表' ,
   'COLUMN_TITLE_MIN_VALUE' => '最小值' ,
   'COLUMN_TITLE_MAX_VALUE' => '最大值' ,
   'COLUMN_TITLE_DISPLAYED_ITEM_COUNT' => '# 個項目顯示了' ,
   'COLUMN_DISABLE_NUMBER_FORMAT' => '停用格式' ,
   'LBL_DROP_DOWN_LIST' => '下拉選單' ,
   'LBL_RADIO_FIELDS' => '單選欄位' ,
   'LBL_MULTI_SELECT_LIST' => '多選清單' ,
   'COLUMN_TITLE_PRECISION' => '精密度' ,
   'MSG_DELETE_CONFIRM' => '您確定要刪除這個項目？' ,
   'POPUP_INSERT_HEADER_TITLE' => '新增自訂欄位' ,
   'POPUP_EDIT_HEADER_TITLE' => '編輯自訂欄位' ,
   'LNK_SELECT_CUSTOM_FIELD' => '選擇自訂欄位' ,
   'LNK_REPAIR_CUSTOM_FIELD' => '修正自訂欄位' ,
   'LBL_MODULE' => '模組' ,
   'COLUMN_TITLE_MASS_UPDATE' => '批次更新' ,
   'COLUMN_TITLE_DUPLICATE_MERGE' => '合併重複資料' ,
   'LBL_LABEL' => '標籤' ,
   'LBL_DATA_TYPE' => '資料類型' ,
   'LBL_DEFAULT_VALUE' => '預設值' ,
   'LBL_AUDITED' => '預設值' ,
   'LBL_REPORTABLE' => '可用在報表' ,
   'ERR_RESERVED_FIELD_NAME' => '保留的關鍵字' ,
   'ERR_SELECT_FIELD_TYPE' => '請選擇一個欄位類型' ,
   'LBL_BTN_ADD' => '新增' ,
   'LBL_BTN_EDIT' => '編輯' );


