<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Groups/language/zh-tw.lang.php, 20080513 Wed 21/05/08 22:54:23 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '群組' ,
   'LBL_GROUP_NAME' => '群組名稱：' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_TEAM' => '團隊：' ,
   'LBL_LIST_TITLE' => '群組' ,
   'LNK_ALL_GROUPS' => '所有群組' ,
   'LNK_NEW_GROUP' => '建立群組' ,
   'LNK_CONVERT_USER' => '轉換使用者到群組' );


