<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/company/language/application/zh-tw.lang.php, 20080513 Mon 16/06/08 21:46:20 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_type_dom' => array (
      '' => '' ,
      'Analyst' => '分析者' ,
      'Competitor' => '競爭者' ,
      'Customer' => '顧客' ,
      'Integrator' => '整合者' ,
      'Investor' => '投資者' ,
      'Partner' => '合作伙伴' ,
      'Press' => '出版商' ,
      'Prospect' => '潛在客戶' ,
      'Reseller' => '批發商' ,
      'Other' => '其他'   ));


