<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Calendar/language/zh-tw.lang.php, 1 Tue 19/02/08 16:08:34 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_list_strings = array ( 
   'dom_cal_month' => array (
      '0' => '' ,
      '1' => '一' ,
      '2' => '二' ,
      '3' => '三' ,
      '4' => '四' ,
      '5' => '五月' ,
      '6' => '六' ,
      '7' => '七' ,
      '8' => '八' ,
      '9' => '九' ,
      '10' => '十' ,
      '11' => '十一' ,
      '12' => '十二'   ),
   'dom_cal_month_long' => array (
      '0' => '' ,
      '1' => '一月' ,
      '2' => '二月' ,
      '3' => '三月' ,
      '4' => '四月' ,
      '5' => '五月' ,
      '6' => '六月' ,
      '7' => '七月' ,
      '8' => '八月' ,
      '9' => '九月' ,
      '10' => '十月' ,
      '11' => '十一月' ,
      '12' => '十二月'   ),
   'dom_cal_weekdays' => array (
      '0' => '日' ,
      '1' => '一' ,
      '2' => '二' ,
      '3' => '三' ,
      '4' => '四' ,
      '5' => '五' ,
      '6' => '六'   ),
   'dom_cal_weekdays_long' => array (
      '0' => '星期日' ,
      '1' => '星期一' ,
      '2' => '星期二' ,
      '3' => '星期三' ,
      '4' => '星期四' ,
      '5' => '星期五' ,
      '6' => '星期六'   ));
$mod_strings = array ( 
   'LBL_MODULE_NAME' => '行事曆' ,
   'LBL_MODULE_TITLE' => '行事曆' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_APPOINTMENT' => '新增約會' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'LNK_CALL_LIST' => '電話' ,
   'LNK_MEETING_LIST' => '會議' ,
   'LNK_TASK_LIST' => '任務' ,
   'LNK_VIEW_CALENDAR' => '今天' ,
   'LBL_MONTH' => '月' ,
   'LBL_DAY' => '日' ,
   'LBL_YEAR' => '年' ,
   'LBL_WEEK' => '週' ,
   'LBL_PREVIOUS_MONTH' => '上個月' ,
   'LBL_PREVIOUS_DAY' => '昨天' ,
   'LBL_PREVIOUS_YEAR' => '去年' ,
   'LBL_PREVIOUS_WEEK' => '上週' ,
   'LBL_NEXT_MONTH' => '下個月' ,
   'LBL_NEXT_DAY' => '明天' ,
   'LBL_NEXT_YEAR' => '明年' ,
   'LBL_NEXT_WEEK' => '下週' ,
   'LBL_AM' => 'AM' ,
   'LBL_PM' => 'PM' ,
   'LBL_SCHEDULED' => '已排程' ,
   'LBL_BUSY' => '忙碌' ,
   'LBL_CONFLICT' => '衝突' ,
   'LBL_USER_CALENDARS' => '使用者行事曆' ,
   'LBL_SHARED' => '分享的' ,
   'LBL_PREVIOUS_SHARED' => '上頁' ,
   'LBL_NEXT_SHARED' => '下一個' ,
   'LBL_SHARED_CAL_TITLE' => '分享的行程' ,
   'LBL_USERS' => '分配給：' ,
   'LBL_REFRESH' => '重新整理' ,
   'LBL_EDIT' => '編輯' ,
   'LBL_SELECT_USERS' => '選擇要顯示行程的使用者' ,
   'LBL_FILTER_BY_TEAM' => '以團隊過濾使用者列表：' );


