<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/chance/language/application/zh-tw.lang.php, 20080513 Sun 18/05/08 10:13:48 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_type_dom' => array (
      '' => '' ,
      'Exsisting Business ' => '已有往來' ,
      'New Business' => '新客戶'   ));


