<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/company/language/application/zh-tw.lang.php, 1 Sat 01/03/08 17:30:27 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '' => '' ,
   'Analyst' => '分析者' ,
   'Competitor' => '競爭者' ,
   'Customer' => '顧客' ,
   'Integrator' => '整合者' ,
   'Investor' => '投資者' ,
   'Partner' => '合作伙伴' ,
   'Press' => '出版商' ,
   'Prospect' => '潛在客戶' ,
   'Reseller' => '批發商' ,
   'Other' => '其他' );


