<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/company/language/application/zh-tw.lang.php, 1 Tue 19/02/08 16:08:34 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_type_dom' => array (
      '' => '' ,
      'Analyst' => '分析師' ,
      'Competitor' => '競爭廠商' ,
      'Customer' => '顧客' ,
      'Integrator' => '系統整合商' ,
      'Investor' => '投資者' ,
      'Partner' => '商業伙伴' ,
      'Press' => '大眾傳播媒體' ,
      'Prospect' => '目標客戶' ,
      'Reseller' => '經銷商' ,
      'Other' => '其他'   ));


