<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s 和你';
$Definition['%s comment'] = '%s 評論';
$Definition['%s comments'] = '%s 評論';
$Definition['%s Connect'] = '%s 連接';
$Definition['%s message'] = '%s 訊息';
$Definition['%s New'] = '%s 新';
$Definition['%s new'] = '%s 新';
$Definition['%s New Plural'] = '%s 新';

$Definition['1 message'] = '1 訊息';

$Definition['About'] = '關於';
$Definition['Accepted'] = '接受';
$Definition['Activity'] = '最新動態';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s 更新了 %6$s 個人資料.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s 更新了 %6$s 個人資料.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s 評論了 %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s 評論了你的 %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s 評論了你的 %8$s.';
$Definition['Activity.Comment'] = '評論';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s 在 %8$s 中提到了 %3$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s 在 %8$s 中提到了 %3$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s 給 %3$s 發送了一個 %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s 給 %3$s 發送了一個 %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s 評論了 %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s 評論了 %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s 在 %8$s 提到了 %3$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s 在 %8$s 提到  %3$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s 匯入了資料.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s 匯入了資料.';
$Definition['Activity.Join.FullHeadline'] = '%1$s 加入.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s 加入.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s 接受了 %4$s 成員申請.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s 接受了 %4$s 成員申請.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s 為 %1$s 建立了帳號.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s 為 %1$s 建立了帳號.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s 接受了 %4$s 的註冊邀請.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s 接受了 %4$s 的註冊邀請.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s 發起了一個 %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s 發起了一個 %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s 修改了 %6$s 資料.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s 修改了 %6$s 個人圖示.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s 修改了 %4$s 權限.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s 修改了 %4$s 權限.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s 登入了.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s 登入了.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s 在 %4$s %5$s 發表了內容.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s 寫道:';
$Definition['Add'] = '新增';
$Definition['Add Comment'] = '新增評論';
$Definition['Add Info &amp; Create Account'] = '新增資訊 &amp; 建立帳號';
$Definition['Add Message'] = '新增訊息';
$Definition['Add People to this Conversation'] = '邀請其他人參與對話';
$Definition['All Conversations'] = '所有對話';
$Definition['All Discussions'] = '所有討論';
$Definition['Allow other members to see your email?'] = '其他成員是否可以看到你的 Email 地址';
$Definition['Announce'] = '公告';
$Definition['Applicants'] = '申請人';
$Definition['Apply'] = '套用';
$Definition['Apply for Membership'] = '申請加入';
$Definition['Are you sure you want to do that?'] = '你確定要這麼做?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = '返回討論';
$Definition['Bookmark'] = '收藏';
$Definition['bookmarked discussion'] = '收藏的討論';
$Definition['Bookmarked Discussions'] = '收藏的討論';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = '請確保你擁有所上傳的文件的版權, 以及圖片不違反本站的服務條款.';

$Definition['Cancel'] = '取消';
$Definition['Categories'] = '分類';
$Definition['Category'] = '分類';
$Definition['Change My Password'] = '修改我的密碼';
$Definition['Change My Picture'] = '修改我的圖示';
$Definition['Close'] = '關閉';
$Definition['comment'] = '評論';
$Definition['Comment'] = '評論';
$Definition['Confirm'] = '確認';
$Definition['Confirm Password'] = '確認密碼';
$Definition['Connect'] = '連接';
$Definition['conversation'] = '對話';
$Definition['Conversations'] = '對話';
$Definition['Create One.'] = '建立一個.';

$Definition['Dashboard'] = '控制台';
$Definition['Date.DefaultDayFormat'] = '%b %e 日';
$Definition['Date.DefaultFormat'] = '%Y %b %e日';
$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = '刪除';
$Definition['Delete Account'] = '刪除帳號';
$Definition['Delete Conversation'] = '刪除對話';
$Definition['Delete Discussion'] = '刪除討論';
$Definition['discussion'] = '討論';
$Definition['Discussion Title'] = '討論主題';
$Definition['Discussions'] = '討論';
$Definition['Don\'t have an account? %s'] = '沒有帳號？ %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = '拖動並縮放下面的方塊, 確定圖示';

$Definition['Edit'] = '編輯';
$Definition['Edit Account'] = '編輯帳號';
$Definition['Edit My Account'] = '編輯我的帳號';
$Definition['Edit My Thumbnail'] = '編輯我的圖示';
$Definition['Edit Preferences'] = '編輯偏好設定';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email 通知';
$Definition['Email Unavailable'] = 'Email 不可用';
$Definition['EmailInvitation'] = '你好!

	%1$s 邀請你加入 %2$s. 歡迎點擊下面的連結加入:

	  %3$s

	  祝你開心每一天！';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

	You have been approved for membership. Sign in now at the following link:

	  %2$s
	    
	  Have a great day！';
$Definition['EmailNotification'] = '%1$s

	Follow the link below to check it out:
	%2$s

	Have a great day！';
$Definition['EmailPassword'] = 'Hello %1$s,

	%2$s has reset your password at %3$s. Your login credentials are now:

	  Email: %6$s
	    Password: %5$s
	      Url: %4$s

	      Have a great day！';
$Definition['EmailStoryNotification'] = '%1$s

	%3$s

	---
	Follow the link below to check it out:
	%2$s

	Have a great day！';
$Definition['EmailWelcome'] = 'Hello %1$s,

	%2$s has created an account for you at %3$s. Your login credentials are:

	  Email: %6$s
	    Password: %5$s
	      Url: %4$s

	      Have a great day！';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

	You have successfully connected to {Title}. Here is your information:

	  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day！';
$Definition['EmailWelcomeRegister'] = 'Hello {User.Name},

	You have successfully registered for an account at {Title}. Here is your information:

	  Username: {User.Name}
  Email: {User.Email}

You can access the site at {/,url,domain}.

Have a great day！';
$Definition['Enter the email address of the person you would like to invite:'] = '請輸入你邀請對象的 Email 地址:';
$Definition['Enter your Email address'] = '輸入你的 Email 地址';
$Definition['Enter your existing account password.'] = '輸入你的帳號密碼.';
$Definition['ErrorCredentials'] = '對不起, 你所輸入的帳號或密碼錯誤.';
$Definition['ErrorPermission'] = '對不起, 沒有權限.';
$Definition['ErrorRecordNotFound'] = '你找尋的資料不存在';
$Definition['ErrorTermsOfService'] = '你必須同意服務條款.';

$Definition['Female'] = '女';
$Definition['Forgot?'] = '忘記了?';

$Definition['Gender'] = '性別';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = '點下面的按鈕可以加入我們！';

$Definition['he'] = '他';
$Definition['her'] = '她的';
$Definition['his'] = '他的';
$Definition['Howdy, Stranger!'] = '你好, 新朋友！';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = '我同意 <a id="TermsOfService" class="Popup" target="terms" href="%s">服務條款</a>';
$Definition['I remember now!'] = '我現在想起了！';
$Definition['In this Conversation'] = '在該對話';
$Definition['Inbox'] = '收件匣';
$Definition['Internal'] = '內部';
$Definition['Invitation Code'] = '邀請碼';
$Definition['Invite'] = '邀請';
$Definition['Invited by'] = '邀請人';

$Definition['Joined'] = '加入';

$Definition['Keep me signed in'] = '記住我的登入狀態';

$Definition['Last Active'] = '最近一次活動';
$Definition['Login with Facebook'] = '使用 Facebook 登入';

$Definition['Male'] = '男';
$Definition['Most recent by %1$s'] = '最近更新 %1$s';
$Definition['My Bookmarks'] = '我的收藏';
$Definition['My Discussions'] = '我的討論';
$Definition['My Drafts'] = '我的草稿';
$Definition['My Invitations'] = '我的邀請';
$Definition['My Preferences'] = '我的偏好設定';

$Definition['Name Unavailable'] = '名字不可用';
$Definition['No discussions were found.'] = '找不到討論';
$Definition['Notifications'] = '通知';
$Definition['Notify me of private messages.'] = '有新私人訊息時通知我.';
$Definition['Notify me when I am added to private conversations.'] = '當我被加入到私人對話中時通知我.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = '當有人在我收藏的討論中評論時通知我.';
$Definition['Notify me when people comment on my discussions.'] = '當有人在我的討論中評論時通知我.';
$Definition['Notify me when people mention me in comments.'] = '當有人在評論中提到我時通知我.';
$Definition['Notify me when people mention me in discussion titles.'] = '當有人在討論標題中提到我時通知我.';
$Definition['Notify me when people reply to my wall comments.'] = '當有人回覆了我的評論時通知我.';
$Definition['Notify me when people write on my wall.'] = '當有人給我留言時通知我.';

$Definition['Okay'] = '確定';
$Definition['On'] = '啟用';
$Definition['Options'] = '選項';
$Definition['Or you can...'] = '或者你可以...';
$Definition['Original'] = '原始圖片';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = '密碼';
$Definition['PasswordRequest'] = '你好 %1$s,

	有人在 %2$s 提出了重設密碼的請求，如果希望重設你的密碼，請點選下面連結：

	  %3$s

	  如果你並沒有提出過，請忽略這封信提到的資訊';
$Definition['Passwords don\'t match'] = '密碼不正確';
$Definition['Permalink'] = '永久連結';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = '頁面切換中，請稍候。如果等待太久，請直接點選 <a href="%s">這裡</a>';
$Definition['Post Comment'] = '發表評論';
$Definition['Post Discussion'] = '發表討論';
$Definition['Powered by Vanilla'] = '以 Vanilla 建置';
$Definition['Preview'] = '預覽';
$Definition['Profile Picture'] = '個人圖示';

$Definition['Recent Activity'] = '最近活動';
$Definition['Recipients'] = '收件人';
$Definition['Redirecting...'] = '重定向...';
$Definition['Remember me on this computer'] = '在這台電腦上記住我';
$Definition['Remove My Picture'] = '刪除我的圖示';
$Definition['Request a new password'] = '遺忘密碼';
$Definition['Roles'] = '角色';

$Definition['Save'] = '儲存';
$Definition['Save Draft'] = '儲存草稿';
$Definition['Save Preferences'] = '儲存偏好設定';
$Definition['Search'] = '搜尋';
$Definition['Select an image on your computer (2mb max)'] = '從電腦中選擇一張圖片(最大 2mb)';
$Definition['Send %s a Message'] = '發送訊息給 %s';
$Definition['Send Message'] = '發送訊息';
$Definition['Sent To'] = '發送給';
$Definition['Share'] = '分享';
$Definition['she'] = '她';
$Definition['Sign In'] = '登入';
$Definition['Sign In with Google'] = '以 Google 帳號登入';
$Definition['Sign In with OpenID'] = '以 OpenID 帳號登入';
$Definition['Sign In with Twitter'] = '以 Twitter 帳號登入';
$Definition['Sign Out'] = '登出';
$Definition['Sign Up'] = '註冊';
$Definition['Sink'] = '下沉';
$Definition['somebody'] = '某人';
$Definition['Start a New Conversation'] = '開啟新對話';
$Definition['Start a New Discussion'] = '開啟新討論';
$Definition['Start Conversation'] = '開啟對話';
$Definition['Started by %1$s'] = '發起人 %1$s';
$Definition['Status'] = '狀態';

$Definition['Thank You!'] = '謝謝！';
$Definition['Thumbnail'] = '圖示';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = '取消訂閱';
$Definition['Upload'] = '上傳';
$Definition['Username'] = '帳號';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s 格式錯誤.';
$Definition['ValidateEnum'] = '%s 無效.';
$Definition['ValidateInteger'] = '%s 不是有效的整數.';
$Definition['ValidateLength'] = '%1$s 內容太長, 超出限制 %2$s 字符.';
$Definition['ValidateMatch'] = '%s 字段不正確.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = '訪問';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = '為什麼你要加入呢?';
$Definition['Write a comment'] = '寫評論';
$Definition['Write Comment'] = '新評論';
$Definition['Write something about yourself...'] = '寫點關於你自己的東西吧...';

$Definition['you'] = '你';
$Definition['You'] = '你';
$Definition['You already have an account here.'] = '你在這裡已經有帳號了.';
$Definition['You are connected as %s through %s.'] = '你以 %s 連結中，透過 %s.';
$Definition['You do not have any conversations.'] = '你沒有參與任何對話.';
$Definition['You do not have any notifications yet.'] = '你沒有任何訊息.';
$Definition['your'] = '你的';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = '你註冊的帳號: <strong>%s</strong>';

/* from plugins */
// FileUpload
$Definition['Insert Image'] = '插入圖片';
$Definition['Uploading...'] = '正在上傳...';
$Definition['Attach a file'] = '新增文件';
$Definition['Attachments'] = '附件';

$Definition['In this Discussion'] = '本討論參與人';

// WhosOnline
$Definition['Who\'s Online'] = '線上會員';
$Definition['Who\'s Online Settings'] = '線上會員設定';
$Definition['Rate of refresh'] = '更新頻率';
$Definition['Frequency'] = '更新頻率';
$Definition['In seconds'] = '秒';

// LastEdited
$Definition['Post edited by %1$s at %2$s'] = '在 %2$s 被 %1$s 編輯';

// PostCount
$Definition['Posts: %s'] = '文章數: %s';
$Definition['Posts'] = '文章數';

// 
$Definition['Quote'] = '引用';
$Definition['%s said:'] = '%s 說:';

// IP
$Definition['Last IP'] = '上次登入IP';

// Following
$Definition['Friends'] = '好友';
$Definition['Followed by %d person'] = '有 %d 人訂閱';
$Definition['Followed by %d people'] = '有 %d 人訂閱';
$Definition['Following %d person'] = '訂閱 %s 人';
$Definition['Following %d people'] = '訂閱 %s 人';
$Definition['Stop following'] = '取消訂閱';
$Definition['Follow %s'] = '訂閱 %s';

// Voteing 部分漢化無法進行
$Definition['Votes'] = '投票';
$Definition['Vote'] = '投票';
$Definition['Follows'] = '訂閱';
$Definition['Views'] = '訪問';
$Definition['Undo Follow'] = '取消訂閱';
$Definition['Follow'] = '訂閱';
$Definition['Popular'] = '最熱';
$Definition['Date Added'] = '發表時間';
$Definition['sorted by'] = '排序依據';

// EasyReply
$Definition['Reply'] = '回覆';

// MarkAllViewd
$Definition['Mark All Viewed'] = '標記所有為已讀';

// Tagging
$Definition['Tags'] = '標籤';
$Definition['Tagged'] = '標籤';


// My hack code
$Definition['Email Or Username'] = '帳號或Email';

// from my found
$Definition['Change Picture'] = '更換圖片';
$Definition['Edit Thumbnail'] = '編輯圖示';
$Definition['Remove Picture'] = '刪除圖片';

$Definition['Save Comment'] = '儲存評論';

$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s 被從 %2$s %3$s 移出, 並加入到 %4$s %5$s.';

$Definition['Unsink'] = '取消下沉';
$Definition['role'] = '角色';
$Definition['Clear'] = '清除';
$Definition['%s messages'] = '%s 訊息';
$Definition['Add a Comment'] = '新增評論';
$Definition['message'] = '訊息';
$Definition['Announcement'] = '公告';
$Definition['Unannounce'] = '取消公告';
$Definition['Old Password'] = '舊密碼';
$Definition['Change Password'] = '修改密碼';
$Definition['Closed'] = '已關閉';
$Definition['Reopen'] = '重新打開';
$Definition['Dismiss'] = '忽略公告';
$Definition['More Discussions'] = '更多討論';
$Definition['You do not have any drafts.'] = '你沒有任何草稿.';
$Definition['Edit Discussion'] = '編輯討論';
$Definition['Comment by %s'] = '被 %s 評論';
$Definition['permalink'] = '永久連結';

$Definition['Your preferences have been saved.'] = '你的偏好設定已儲存';

$Definition["↳ No results for '%s'"] = " '%s' 沒有任何結果";
$Definition["↳ Search results for '%s'"] = "↳ '%s' 的搜尋結果";

$Definition['More Results'] = '更多結果';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = '該圖片為適合頁面被自動縮小. 查看大圖請點擊.';
$Definition['Just you!'] = '只有你！';
$Definition['%s deleted this conversation.'] = '%s 刪除了該對話';

$Definition['Body'] = '正文';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = '你已經在 %2$s 秒內發貼 %1$s 次, 為防止惡意灌水, 請等待 %3$s 秒後再重新文章.';

$Definition['Draft saved at %s'] = '草稿在 %s 被儲存';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = '帳號不能包含非法字符. 長度不能少於3字符.';
$Definition['[%s] Invitation'] = '[%s] 邀請你加入';
$Definition['You have %s invitations left for this month.'] = '你本月還可以發送 %s 條邀請.';
$Definition['Your invitation has been sent.'] = '你的邀請已經發送';
$Definition['Uninvite'] = '取消邀請';
$Definition['Send Again'] = '重新發送';
$Definition['Pending'] = '等待接受';
$Definition['On'] = '時間';
$Definition['The invitation was removed successfully.'] = '邀請已經成功刪除.';
$Definition['An invitation has already been sent to the email you entered.'] = '已經有其他用戶的邀請發送給該地址.';
$Definition['The email you have entered is already related to an existing account.'] = '該郵件地址已經是網站的成員.';
