<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Home/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_NEW_FORM_TITLE' => '新增聯絡人' ,
   'LBL_FIRST_NAME' => '姓名：' ,
   'LBL_LAST_NAME' => '姓氏：' ,
   'LBL_LIST_LAST_NAME' => '姓氏' ,
   'LBL_ACCOUNT_NAME' => '客戶名稱：' ,
   'LBL_LIST_ACCOUNT_NAME' => '客戶名稱' ,
   'LBL_PHONE' => '電話：' ,
   'LBL_EMAIL_ADDRESS' => '電子郵件：' ,
   'LBL_TOTAL' => '總計：' ,
   'LBL_MY_HOME' => '我的首頁' ,
   'LBL_MODIFIED_TIME' => '修改時間' ,
   'LBL_LOGIN_ID' => '代號' ,
   'LBL_MODIFIED_BY' => '修改者' ,
   'LBL_TYPE' => '檔案類型' ,
   'LBL_PIPELINE_FORM_TITLE' => '我的統計圖表' ,
   'ERR_ONE_CHAR' => '請至少輸入1個字元以上的號碼，以供搜尋 ...' ,
   'LBL_OPEN_TASKS' => '我的進行中任務' ,
   'LBL_LEADS_BY_SOURCE' => '準客戶來源' ,
   'LBL_LEADS_BY_STATUS' => '準客戶狀態' ,
   'LBL_UPCOMING_EVENTS' => '即將到來的行程' ,
   'LBL_PENDING_EVENTS' => '等待中的行程' ,
   'LBL_SINGLE_PENDING_EVENT' => '最近十天事件' ,
   'LBL_MULTIPLE_PENDING_EVENTS' => '最近十天事件' ,
   'recordsforuser' => '資料於' ,
   'Today' => '今日事項' ,
   'This Week' => '這星期' ,
   'This Month' => '這個月' ,
   'This Year' => '今年' ,
   'Last Week' => '上星期' ,
   'Last 2 Days' => '過去兩天' ,
   'Last Ten Days' => '過去十天' ,
   'TITLE_AJAX_CSS_POPUP_CHAT' => '聊天室' ,
   'User List' => '使用者列表' );


