<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Bugs/language/zh-tw.lang.php, 20080502 Fri 02/05/08 22:46:02 
  * Description : 20080502.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '問題' ,
   'LBL_MODULE_TITLE' => '問題追蹤：首頁' ,
   'LBL_MODULE_ID' => '問題' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋問題' ,
   'LBL_LIST_FORM_TITLE' => '問題清單' ,
   'LBL_NEW_FORM_TITLE' => '新的問題' ,
   'LBL_CONTACT_BUG_TITLE' => '問題聯絡人：' ,
   'LBL_SUBJECT' => '主旨：' ,
   'LBL_BUG' => '問題：' ,
   'LBL_BUG_NUMBER' => '問題編號：' ,
   'LBL_NUMBER' => '數字：' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_CONTACT_NAME' => '聯絡人名稱：' ,
   'LBL_BUG_SUBJECT' => '問題主旨：' ,
   'LBL_CONTACT_ROLE' => '角色：' ,
   'LBL_LIST_NUMBER' => '數字' ,
   'LBL_LIST_SUBJECT' => '主旨' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_LIST_PRIORITY' => '優先' ,
   'LBL_LIST_RELEASE' => '版本' ,
   'LBL_LIST_RESOLUTION' => '分析' ,
   'LBL_LIST_LAST_MODIFIED' => '最新修改' ,
   'LBL_INVITEE' => '聯絡人' ,
   'LBL_TYPE' => '類型：' ,
   'LBL_LIST_TYPE' => '類型' ,
   'LBL_RESOLUTION' => '分析：' ,
   'LBL_RELEASE' => '版本：' ,
   'LNK_NEW_BUG' => '回報問題' ,
   'LNK_BUG_LIST' => '問題' ,
   'NTC_REMOVE_INVITEE' => '您確定要從這個問題中移除這個聯絡人？' ,
   'NTC_REMOVE_ACCOUNT_CONFIRMATION' => '您確定要從這個帳號中移除這個問題？' ,
   'ERR_DELETE_RECORD' => '要刪除問題需要輸入記錄編號' ,
   'LBL_LIST_MY_BUGS' => '指派給我的問題' ,
   'LBL_FOUND_IN_RELEASE' => '有問題版本：' ,
   'LBL_FIXED_IN_RELEASE' => '已修正版本：' ,
   'LBL_LIST_FIXED_IN_RELEASE' => '已修正版本' ,
   'LBL_WORK_LOG' => '工作記錄' ,
   'LBL_SOURCE' => '來源' ,
   'LBL_PRODUCT_CATEGORY' => '產品類別' ,
   'LBL_CREATED_BY' => '建立者：' ,
   'LBL_DATE_CREATED' => '建立日期：' ,
   'LBL_MODIFIED_BY' => '最後更新者：' ,
   'LBL_DATE_LAST_MODIFIED' => '更新日期：' ,
   'LBL_LIST_EMAIL_ADDRESS' => '郵件' ,
   'LBL_LIST_CONTACT_NAME' => '聯絡人' ,
   'LBL_LIST_ACCOUNT_NAME' => '帳號' ,
   'LBL_LIST_PHONE' => '電話' ,
   'NTC_DELETE_CONFIRMATION' => '您確定要從這個問題中移除這個聯絡人？' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '問題追蹤' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => '待辦事項' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => '紀錄' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => '聯絡人' ,
   'LBL_ACCOUNTS_SUBPANEL_TITLE' => '公司' ,
   'LBL_CASES_SUBPANEL_TITLE' => '案件' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => '專案' ,
   'LBL_SYSTEM_ID' => '系統編號' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => '指派的使用者' ,
   'LBL_ASSIGNED_TO_NAME' => '指派給' );


