<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Roles/language/zh-tw.lang.php, 1 Sat 16/02/08 06:32:44 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ROLE' => '角色：' ,
   'LBL_LANGUAGE' => '語言：' ,
   'LBL_MODULE_NAME' => '角色' ,
   'LBL_MODULE_TITLE' => '角色：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋角色' ,
   'LBL_LIST_FORM_TITLE' => '角色列表' ,
   'LNK_NEW_ROLE' => '建立角色' ,
   'LNK_ROLES' => '角色' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_DESCRIPTION' => '說明：' ,
   'LBL_ALLOWED_MODULES' => '可以使用模組：' ,
   'LBL_DISALLOWED_MODULES' => '不可使用模組：' ,
   'LBL_ASSIGN_MODULES' => '編輯模組：' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '角色' ,
   'LBL_USERS' => '使用者' ,
   'LBL_USERS_SUBPANEL_TITLE' => '使用者' );


