<?PHP // $Id$ 
      // role.php - created with Moodle 1.8.2+ (2007021520)


$string['addrole'] = '新增一個角色';
$string['allow'] = '允許';
$string['allowassign'] = '允許角色指派';
$string['allowoverride'] = '允許角色覆蓋';
$string['assignglobalroles'] = '指定全域角色';
$string['assignroles'] = '指定角色';
$string['blog:create'] = '建立新的部落格資料';
$string['blog:manageentries'] = '編輯與管理資料';
$string['blog:manageofficialtags'] = '管理正式標籤';
$string['blog:managepersonaltags'] = '管理個人標籤';
$string['blog:view'] = '檢視部落格資料';
$string['calendar:manageentries'] = '管理任何行事曆資料';
$string['calendar:manageownentries'] = '管理自己的行事曆資料';
$string['capabilities'] = '能力';
$string['capability'] = '能力';
$string['category:create'] = '建立類別';
$string['category:delete'] = '刪除類別';
$string['category:update'] = '更新類別';
$string['category:visibility'] = '檢視隱藏類別';
$string['course:activityvisibility'] = '隱藏/顯示活動';
$string['course:bulkmessaging'] = '發送訊息給許多人';
$string['course:create'] = '建立課程';
$string['course:delete'] = '刪除課程';
$string['course:manageactivities'] = '管理活動';
$string['course:managefiles'] = '管理檔案';
$string['course:managegrades'] = '管理分數';
$string['course:managegroups'] = '管理群組';
$string['course:managemetacourse'] = '管理後設課程';
$string['course:managescales'] = '管理評量';
$string['course:reset'] = '重設課程';
$string['course:sectionvisibility'] = '控制區域顯示';
$string['course:setcurrentsection'] = '設定目前區域';
$string['course:update'] = '更新課程設定';
$string['course:useremail'] = '啟用/停用郵件住址';
$string['course:view'] = '檢視課程';
$string['course:viewcoursegrades'] = '檢視課程分數';
$string['course:viewhiddenactivities'] = '檢視隱藏活動';
$string['course:viewhiddencourses'] = '檢視隱藏課程';
$string['course:viewhiddensections'] = '檢視隱藏區域';
$string['currentrole'] = '現在的角色';
$string['defaultrole'] = '預設的角色';
$string['defineroles'] = '定義角色';
$string['editrole'] = '編輯角色';
$string['manageroles'] = '管理角色';
$string['permissions'] = '權限';
$string['roleassignments'] = '分配角色';
$string['roles'] = '角色';
$string['selectrole'] = '選擇一個角色';
$string['showallroles'] = '顯示所有角色';
$string['site:restore'] = '還原課程';
$string['site:viewreports'] = '檢視報表';
$string['user:create'] = '建立使用者';
$string['user:delete'] = '刪除使用者';

?>
