<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SavedSearch/language/zh-tw.lang.php, 20080513 Sun 18/05/08 10:13:48 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_TITLE' => '我已儲存搜尋結果' ,
   'LBL_SEARCH_FORM_TITLE' => '我已儲存搜尋結果：搜尋' ,
   'LBL_LIST_FORM_TITLE' => '我已儲存搜尋結果列表' ,
   'LBL_DELETE_CONFIRM' => '您確定要刪除指定的已儲存搜尋結果' ,
   'LBL_UPDATE_BUTTON_TITLE' => '更新這個儲存的搜尋' ,
   'LBL_DELETE_BUTTON_TITLE' => '刪除這個已儲存搜尋結果' ,
   'LBL_SAVE_BUTTON_TITLE' => '儲存目前搜尋' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_MODULE' => '模組' ,
   'LBL_ORDER_BY_COLUMNS' => '排序：' ,
   'LBL_DIRECTION' => '方向：' ,
   'LBL_SAVE_SEARCH_AS' => '儲存搜尋：' ,
   'LBL_SAVE_SEARCH_AS_HELP' => '這將會儲存您的檢視設定與進階搜尋標籤中的規則' ,
   'LBL_PREVIOUS_SAVED_SEARCH' => '上一個儲存的搜尋：' ,
   'LBL_PREVIOUS_SAVED_SEARCH_HELP' => '編輯與刪除儲存的搜尋。' ,
   'LBL_ASCENDING' => '升冪' ,
   'LBL_DESCENDING' => '降冪' ,
   'LBL_MODIFY_CURRENT_SEARCH' => '修改目前搜尋' );


