<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Tasks/language/zh-tw.lang.php, 1 Mon 03/03/08 16:17:38 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '任務' ,
   'LBL_TASK' => '任務：' ,
   'LBL_MODULE_TITLE' => ' 任務：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => ' 搜尋任務' ,
   'LBL_LIST_FORM_TITLE' => ' 任務列表' ,
   'LBL_NEW_FORM_TITLE' => ' 新增任務' ,
   'LBL_NEW_FORM_SUBJECT' => '主旨：' ,
   'LBL_NEW_FORM_DUE_DATE' => '到期日期：' ,
   'LBL_NEW_FORM_DUE_TIME' => '到期時間：' ,
   'LBL_NEW_TIME_FORMAT' => '(24:00)' ,
   'LBL_LIST_CLOSE' => '關閉' ,
   'LBL_LIST_SUBJECT' => '主旨' ,
   'LBL_LIST_CONTACT' => '聯絡人' ,
   'LBL_LIST_PRIORITY' => '優先' ,
   'LBL_LIST_RELATED_TO' => '相關' ,
   'LBL_LIST_DUE_DATE' => '到期' ,
   'LBL_LIST_DUE_TIME' => '結束時間' ,
   'LBL_SUBJECT' => '主旨：' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_DUE_DATE' => '到期日期：' ,
   'LBL_DUE_TIME' => '到期時間：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_COLON' => '：' ,
   'LBL_DUE_DATE_AND_TIME' => '結束日期與時間：' ,
   'LBL_START_DATE_AND_TIME' => '開始日期、時間：' ,
   'LBL_START_DATE' => '開始日期：' ,
   'LBL_LIST_START_DATE' => '開始日期' ,
   'LBL_START_TIME' => '開始時間：' ,
   'LBL_LIST_START_TIME' => '開始時間' ,
   'DATE_FORMAT' => '(yyyy-mm-dd)' ,
   'LBL_NONE' => '無' ,
   'LBL_CONTACT' => '聯絡人：' ,
   'LBL_EMAIL_ADDRESS' => '電子郵件地址：' ,
   'LBL_PHONE' => '電話：' ,
   'LBL_EMAIL' => '電子郵件：' ,
   'LBL_DESCRIPTION_INFORMATION' => '描述資訊' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_CONTACT_NAME' => '聯絡名: ' ,
   'LBL_LIST_COMPLETE' => '完成：' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_DATE_DUE_FLAG' => '沒有結束日期' ,
   'LBL_DATE_START_FLAG' => '沒有開始日期' ,
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除機會.' ,
   'ERR_INVALID_HOUR' => '請輸入 0 至 24 之間的小時數' ,
   'LBL_DEFAULT_STATUS' => 'Not Started' ,
   'LBL_DEFAULT_PRIORITY' => 'Medium' ,
   'LBL_LIST_MY_TASKS' => '我要完成的任務' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_EMAIL' => '保留信件' ,
   'LNK_CALL_LIST' => '電話' ,
   'LNK_MEETING_LIST' => '會議' ,
   'LNK_TASK_LIST' => '任務' ,
   'LNK_NOTE_LIST' => '備註' ,
   'LNK_EMAIL_LIST' => '電子郵件' ,
   'LNK_VIEW_CALENDAR' => '今天' ,
   'LBL_CONTACT_FIRST_NAME' => '聯絡人名' ,
   'LBL_CONTACT_LAST_NAME' => '聯絡人姓' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => '指派的使用者' ,
   'LBL_ASSIGNED_TO_NAME' => '分配給：' );


