<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Dashboard/language/zh-tw.lang.php, 20080513 Mon 16/06/08 21:46:20 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '概要' ,
   'LBL_MODULE_TITLE' => '統計圖：首頁' ,
   'LNK_NEW_ACCOUNT' => '新增客戶' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_CASE' => '建立案件' ,
   'LNK_NEW_CONTACT' => '建立聯絡人' ,
   'LNK_NEW_ISSUE' => '回報問題' ,
   'LNK_NEW_LEAD' => '建立準客戶' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_OPPORTUNITY' => '建立機會' ,
   'LNK_NEW_QUOTE' => '建立報價單' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'LBL_ADD_A_CHART' => '新增圖表' ,
   'LBL_DELETE_FROM_DASHBOARD' => '刪除統計表' ,
   'LBL_MOVE_DOWN' => '上移' ,
   'LBL_MOVE_UP' => '下移' ,
   'LBL_BASIC_CHARTS' => '-- 基本圖表 --' ,
   'LBL_PUBLISHED_REPORTS' => '-- 已發佈報表 --' ,
   'LBL_MY_REPORTS' => '-- 我的報表 --' ,
   'LBL_TEAM_REPORTS' => '-- 團隊報表 --' ,
   'LBL_REPORT_NO_CHART' => '這個報表沒有圖形' ,
   'LBL_MOVE_CHARTS' => '（點選圖表名稱來移動到其他位置）' ,
   'LBL_DASHBOARD_PAGE_1' => '統計首頁' ,
   'LBL_DASHBOARD_PAGE_2' => '銷售統計' );


