<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Currencies/language/zh-tw.lang.php,  Wed 20/02/08 14:57:08 
  * Description : .
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '貨幣' ,
   'LBL_LIST_FORM_TITLE' => '貨幣' ,
   'LBL_CURRENCY' => '貨幣' ,
   'LBL_ADD' => '新增' ,
   'LBL_MERGE' => '合併' ,
   'LBL_MERGE_TXT' => '請檢查您希望與選擇貨幣對應的貨幣，這將會刪除所有貨幣資訊接著從選擇的貨幣重新指定。' ,
   'LBL_US_DOLLAR' => '美金' ,
   'LBL_DELETE' => '刪除' ,
   'LBL_LIST_SYMBOL' => '貨幣符號' ,
   'LBL_LIST_NAME' => '貨幣名稱' ,
   'LBL_LIST_ISO4217' => 'ISO 4217 編碼' ,
   'LBL_UPDATE' => '更新' ,
   'LBL_LIST_RATE' => '匯率' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LNK_NEW_CONTACT' => '新增聯絡人' ,
   'LNK_NEW_ACCOUNT' => '新增客戶' ,
   'LNK_NEW_OPPORTUNITY' => '新增機會' ,
   'LNK_NEW_CASE' => '新增案件' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_CALL' => '新增電話記錄' ,
   'LNK_NEW_EMAIL' => '新增電子郵件' ,
   'LNK_NEW_MEETING' => '新增會議' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'NTC_DELETE_CONFIRMATION' => '您確定要刪除這筆記錄？建議您可以先停用這筆記錄，否則所有的資料在存取時都會轉換為美金。' ,
   'currency_status_dom' => array (
      'Active' => '有效' ,
      'Inactive' => '無效'   ));


