<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProjectTask/language/zh-tw.lang.php, 1 Sat 16/02/08 08:01:39 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '專案任務' ,
   'LBL_MODULE_TITLE' => '專案任務：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋專案任務' ,
   'LBL_LIST_FORM_TITLE' => '專案任務列表' ,
   'LBL_ID' => '編號：' ,
   'LBL_DATE_ENTERED' => '輸入日期：' ,
   'LBL_DATE_MODIFIED' => '修改日期：' ,
   'LBL_ASSIGNED_USER_ID' => '指派給：' ,
   'LBL_MODIFIED_USER_ID' => '修改者編號：' ,
   'LBL_CREATED_BY' => '建立者：' ,
   'LBL_TEAM_ID' => '團隊：' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_DATE_DUE' => '到期日期：' ,
   'LBL_TIME_DUE' => '到期時間：' ,
   'LBL_DATE_START' => '開始日期：' ,
   'LBL_TIME_START' => '開始時間：' ,
   'LBL_DURATION' => '活動期間：' ,
   'LBL_PARENT_ID' => '專案：' ,
   'LBL_PERCENT_COMPLETE' => '進度（%）：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_ORDER_NUMBER' => '順序：' ,
   'LBL_TASK_NUMBER' => '任務編號：' ,
   'LBL_DEPENDS_ON_ID' => '依存關係：' ,
   'LBL_MILESTONE_FLAG' => '里程碑：' ,
   'LBL_ESTIMATED_EFFORT' => '估計工作量（小時）：' ,
   'LBL_ACTUAL_EFFORT' => '實際工作量（小時）：' ,
   'LBL_UTILIZATION' => '使用率（%）：' ,
   'LBL_DELETED' => '刪除：' ,
   'LBL_LIST_ORDER_NUMBER' => '訂單' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_PARENT_NAME' => '專案' ,
   'LBL_LIST_PERCENT_COMPLETE' => '進度（%）' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_LIST_DURATION' => '時間' ,
   'LBL_LIST_ASSIGNED_USER_ID' => '指派給' ,
   'LBL_LIST_DATE_DUE' => '結束日期' ,
   'LBL_LIST_DATE_START' => '開始日期' ,
   'LBL_LIST_PRIORITY' => '優先' ,
   'LBL_LIST_CLOSE' => '關閉' ,
   'LBL_PROJECT_NAME' => '專案名稱' ,
   'LNK_NEW_PROJECT' => '建立專案' ,
   'LNK_PROJECT_LIST' => '專案列表' ,
   'LNK_NEW_PROJECT_TASK' => '建立專案任務' ,
   'LNK_PROJECT_TASK_LIST' => '專案任務' ,
   'LBL_LIST_MY_PROJECT_TASKS' => '我未完成的專案任務' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '專案任務' ,
   'LBL_NEW_FORM_TITLE' => '新增專案任務' ,
   'LBL_ACTIVITIES_TITLE' => '待辦事項' ,
   'LBL_HISTORY_TITLE' => '紀錄' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => '待辦事項' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => '紀錄' ,
   'DATE_JS_ERROR' => '請輸入與已輸入時間一致的日期' ,
   'LBL_ASSIGNED_USER_NAME' => '指派給' ,
   'LBL_PARENT_NAME' => '專案名稱' );


