<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SchedulersJobs/language/zh-tw.lang.php, 1 Tue 19/02/08 16:08:34 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_EXECUTE_TIME' => '執行時間' );


