<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/MailMerge/language/zh-tw.lang.php, 20080502 Fri 02/05/08 22:46:02 
  * Description : 20080502.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_STEP_1' => '第一步：選擇模組與樣板' ,
   'LBL_MAILMERGE_MODULE' => '選擇模組：' ,
   'LBL_MAILMERGE_SELECTED_MODULE' => '選擇的模組：' ,
   'LBL_MAILMERGE_TEMPLATES' => '選擇樣板：' ,
   'LBL_STEP_2' => '第二步：選擇要合併的物件' ,
   'LBL_MAILMERGE_OBJECTS' => '選擇物件：' ,
   'LBL_STEP_3' => '設定聯絡人集合' ,
   'LBL_STEP_4' => '預覽與完成' ,
   'LBL_SELECTED_MODULE' => '選擇的模組：' ,
   'LBL_SELECTED_TEMPLATE' => '選擇的樣板：' ,
   'LBL_SELECTED_ITEMS' => '選擇的項目：' ,
   'LBL_STEP_5' => '郵件合併完成' ,
   'LBL_MERGED_FILE' => '合併的檔案：' ,
   'LNK_NEW_MAILMERGE' => '開始郵件合併' ,
   'LNK_UPLOAD_TEMPLATE' => '上傳樣板' ,
   'LBL_DOC_NAME' => '文件名稱：' ,
   'LBL_FILENAME' => '檔案名稱：' ,
   'LBL_DOC_VERSION' => '版本：' ,
   'LBL_DOC_DESCRIPTION' => '描述：' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_RELATIONSHIP' => '設定聯絡人關聯' ,
   'LBL_FINISH' => '開始合併' ,
   'LBL_NEXT' => '下一 >' ,
   'LBL_BACK' => '< 上一' ,
   'LBL_START' => '重新開始' ,
   'LBL_TEMPLATE_NOTICE' => '樣板是包含合併欄位的 Microsoft Word 文件，事先透過文件模組上傳與儲存。' ,
   'LBL_CONTAINS_CONTACT_INFO' => '選擇的樣板包含聯絡人資訊。' ,
   'LBL_ADDIN_NOTICE' => '這個功能需要您先安裝郵件合併外掛到 Microsoft Word。' ,
   'LBL_BROWSER_NOTICE' => '要執行實際的合併您必須執行 IE 6.0 或更新的版本。' );


