<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/person/language/zh-tw.lang.php, 20080503 Tue 13/05/08 18:40:34 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_SALUTATION' => '問候' ,
   'LBL_NAME' => '名稱' ,
   'LBL_FIRST_NAME' => '姓名' ,
   'LBL_LAST_NAME' => '姓氏' ,
   'LBL_TITLE' => '標題' ,
   'LBL_DEPARTMENT' => '部門' ,
   'LBL_DO_NOT_CALL' => '拒絕打擾' ,
   'LBL_HOME_PHONE' => '家庭電話：' ,
   'LBL_MOBILE_PHONE' => '手機' ,
   'LBL_OFFICE_PHONE' => '公司電話：' ,
   'LBL_OTHER_PHONE' => '其它：' ,
   'LBL_FAX_PHONE' => '傳真：' ,
   'LBL_EMAIL_ADDRESS' => '信箱' ,
   'LBL_PRIMARY_ADDRESS' => '主地址：' ,
   'LBL_PRIMARY_ADDRESS_STREET' => '主地址：' ,
   'LBL_PRIMARY_ADDRESS_STREET_2' => '[主要住址]街道巷弄2：' ,
   'LBL_PRIMARY_ADDRESS_STREET_3' => '[主要住址]街道巷弄3：' ,
   'LBL_PRIMARY_ADDRESS_CITY' => '[主要]鄉鎮市區' ,
   'LBL_PRIMARY_ADDRESS_STATE' => '[主要]縣市' ,
   'LBL_PRIMARY_ADDRESS_POSTALCODE' => '[主要]郵遞區號' ,
   'LBL_PRIMARY_ADDRESS_COUNTRY' => '[主要住址]國家：' ,
   'LBL_ALT_ADDRESS_STREET' => '[其他]住址' ,
   'LBL_ALT_ADDRESS_STREET_2' => '[其他住址]巷弄2：' ,
   'LBL_ALT_ADDRESS_STREET_3' => '[其他住址]巷弄3：' ,
   'LBL_ALT_ADDRESS_CITY' => '[其他]鄉鎮市區' ,
   'LBL_ALT_ADDRESS_STATE' => '[其他]縣市' ,
   'LBL_ALT_ADDRESS_POSTALCODE' => '[其他]郵遞區號' ,
   'LBL_ALT_ADDRESS_COUNTRY' => '[其他]國家' ,
   'LBL_COUNTRY' => '國家：' ,
   'LBL_STREET' => '其他住址' ,
   'LBL_CITY' => 'City' ,
   'LBL_STATE' => '省份' ,
   'LBL_POSTALCODE' => '郵遞區號：' ,
   'LBL_POSTAL_CODE' => '郵遞區號：' ,
   'lbl_contact_information' => '聯絡資訊' ,
   'LBL_ADDRESS_INFORMATION' => '住址' ,
   'LBL_CONTACT_INFORMATION' => '聯絡資訊' ,
   'LBL_ASSIGNED_TO_NAME' => '指派給' ,
   'LBL_ASSISTANT' => '助理' ,
   'LBL_ASSISTANT_PHONE' => '助理電話' ,
   'LBL_WORK_PHONE' => '公司電話：' );


