<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Charts/language/zh-tw.lang.php, 20080513 Wed 21/05/08 22:54:23 
  * Description : 20080513.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_NO_OPPS' => '請建立一些機會來顯示機會圖表。' ,
   'LBL_ALL_OPPORTUNITIES' => '所有機會的總金額' ,
   'LBL_CHART_TYPE' => '圖表類型:' ,
   'LBL_CREATED_ON' => '上次執行時間' ,
   'LBL_DATE_END' => '結束日期：' ,
   'LBL_DATE_RANGE_TO' => '到' ,
   'LBL_DATE_RANGE' => '日期範圍' ,
   'LBL_DATE_START' => '開始日期：' ,
   'LBL_EDIT' => '編輯' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME_DESC' => '根據選擇使用者結果的指定準客戶來源顯示累積機會金額，結果是基於銷售策略為成功結案、失敗結案或是其他設定。' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME' => '所有準客戶的機會結果' ,
   'LBL_LEAD_SOURCE_FORM_DESC' => '顯示選擇使用者的指定準客戶來源累積機會金額' ,
   'LBL_LEAD_SOURCE_FORM_TITLE' => '準客戶來源的所有機會' ,
   'LBL_LEAD_SOURCE_OTHER' => '其他' ,
   'LBL_LEAD_SOURCES' => '準客戶來源：' ,
   'LBL_MODULE_NAME' => '概要' ,
   'LBL_MODULE_TITLE' => '統計圖：首頁' ,
   'LBL_MONTH_BY_OUTCOME_DESC' => '顯示選擇使用者的每月累積機會金額結果，預期結案日期為指定的日期範圍，結果是基於銷售策略為成功結案、失敗結案或是其他設定。' ,
   'LBL_OPP_SIZE' => '機會大小於' ,
   'LBL_OPP_THOUSANDS' => 'K' ,
   'LBL_OPPS_IN_LEAD_SOURCE' => '機會來源的準客戶是' ,
   'LBL_OPPS_IN_STAGE' => '銷售策略是' ,
   'LBL_OPPS_OUTCOME' => '結果是' ,
   'LBL_OPPS_WORTH' => '機會價值' ,
   'LBL_PIPELINE_FORM_TITLE_DESC' => '顯示您的機會中指定銷售策略的累積金額，預期結案日期為指定的日期範圍。' ,
   'LBL_CAMPAIGN_ROI_TITLE_DESC' => '依據收入與投資顯示活動回應。' ,
   'LBL_REFRESH' => '重新整理' ,
   'LBL_ROLLOVER_DETAILS' => '點選長條圖來瀏覽細節。' ,
   'LBL_ROLLOVER_WEDGE_DETAILS' => '點選圖形來顯示細節。' ,
   'LBL_SALES_STAGE_FORM_DESC' => '顯示指定使用者於選擇的銷售策略中累積機會金額，預期結案日期為指定的日期範圍。' ,
   'LBL_SALES_STAGE_FORM_TITLE' => '銷售策略的長條圖' ,
   'LBL_SALES_STAGES' => '銷售策略：' ,
   'LBL_TOTAL_PIPELINE' => '統計圖總和' ,
   'LBL_USERS' => '使用者：' ,
   'LBL_YEAR_BY_OUTCOME' => '每月結果的長條圖' ,
   'LBL_YEAR' => '年：' ,
   'LNK_NEW_ACCOUNT' => '新增客戶' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_CASE' => '建立案件' ,
   'LNK_NEW_CONTACT' => '建立聯絡人' ,
   'LNK_NEW_ISSUE' => '回報問題' ,
   'LNK_NEW_LEAD' => '建立準客戶' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_OPPORTUNITY' => '建立機會' ,
   'LNK_NEW_QUOTE' => '建立報價單' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'NTC_NO_LEGENDS' => '無' ,
   'LBL_TITLE' => '標題: ' );


