<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACLRoles/language/zh-tw.lang.php, 20080503 Tue 13/05/08 18:40:34 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '角色' ,
   'LBL_MODULE_TITLE' => '角色：首頁' ,
   'LBL_ROLE' => '角色' ,
   'LBL_NAME' => '名稱' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LIST_ROLES' => '角色列表' ,
   'LBL_USERS_SUBPANEL_TITLE' => '使用者' ,
   'LIST_ROLES_BY_USER' => '依使用者列出角色' ,
   'LBL_ROLES_SUBPANEL_TITLE' => '使用者角色' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋' ,
   'LBL_CREATE_ROLE' => '建立角色' ,
   'LBL_EDIT_VIEW_DIRECTIONS' => '雙擊儲存格來修改數值。' ,
   'LBL_ACCESS_DEFAULT' => '預設' ,
   'LBL_ALL' => '全部' );


