<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Project/language/zh-tw.lang.php, 1 Sat 16/02/08 08:01:39 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '專案' ,
   'LBL_MODULE_TITLE' => '專案：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋專案' ,
   'LBL_LIST_FORM_TITLE' => '專案列表' ,
   'LBL_HISTORY_TITLE' => '紀錄' ,
   'LBL_ID' => '編號：' ,
   'LBL_DATE_ENTERED' => '輸入日期：' ,
   'LBL_DATE_MODIFIED' => '修改日期：' ,
   'LBL_ASSIGNED_USER_ID' => '指派給：' ,
   'LBL_ASSIGNED_USER_NAME' => '分配給：' ,
   'LBL_MODIFIED_USER_ID' => '修改者編號：' ,
   'LBL_CREATED_BY' => '建立者：' ,
   'LBL_TEAM_ID' => '團隊：' ,
   'LBL_NAME' => '名稱：' ,
   'LBL_PDF_PROJECT_NAME' => '專案名稱:' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_DELETED' => '刪除：' ,
   'LBL_DATE' => '日期:' ,
   'LBL_DATE_START' => '開始日期：' ,
   'LBL_DATE_END' => '結束日期：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_MY_PROJECT_TASKS' => '我未完成的專案任務' ,
   'LBL_TOTAL_ESTIMATED_EFFORT' => '估計總工作量（小時）：' ,
   'LBL_TOTAL_ACTUAL_EFFORT' => '實際總工作量（小時）：' ,
   'LBL_LIST_NAME' => '名稱' ,
   'LBL_LIST_ASSIGNED_USER_ID' => '指派給' ,
   'LBL_LIST_TOTAL_ESTIMATED_EFFORT' => '估計總工作量（小時）' ,
   'LBL_LIST_TOTAL_ACTUAL_EFFORT' => '實際總工作量（小時）' ,
   'LBL_LIST_END_DATE' => '結束日期' ,
   'LBL_LIST_TEAM_ID' => '團隊' ,
   'LBL_PROJECT_SUBPANEL_TITLE' => '專案' ,
   'LBL_PROJECT_TASK_SUBPANEL_TITLE' => '專案任務' ,
   'LBL_CONTACT_SUBPANEL_TITLE' => '聯絡人' ,
   'LBL_ACCOUNT_SUBPANEL_TITLE' => '公司' ,
   'LBL_OPPORTUNITY_SUBPANEL_TITLE' => '機會' ,
   'LBL_QUOTE_SUBPANEL_TITLE' => '報價單' ,
   'LBL_NEW_FORM_TITLE' => '新增專案' ,
   'CONTACT_REMOVE_PROJECT_CONFIRM' => '您確定要從這個專案中刪除聯絡人？' ,
   'LNK_NEW_PROJECT' => '建立專案' ,
   'LNK_PROJECT_LIST' => '專案列表' ,
   'LNK_NEW_PROJECT_TASK' => '建立專案任務' ,
   'LNK_PROJECT_TASK_LIST' => '專案任務' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '專案' ,
   'LBL_ACTIVITIES_TITLE' => '待辦事項' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => '待辦事項' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => '紀錄' ,
   'LBL_QUICK_NEW_PROJECT' => '新增專案' ,
   'LBL_PROJECT_TASKS_SUBPANEL_TITLE' => '專案任務' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => '聯絡人' ,
   'LBL_ACCOUNTS_SUBPANEL_TITLE' => '公司' ,
   'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => '機會' ,
   'LBL_CASES_SUBPANEL_TITLE' => '案件' ,
   'LBL_BUGS_SUBPANEL_TITLE' => '問題' ,
   'LBL_PRODUCTS_SUBPANEL_TITLE' => '產品' ,
   'LBL_TASK_ID' => '編號' ,
   'LBL_DURATION' => '時間' ,
   'LBL_START' => '開始' ,
   'LBL_FINISH' => '完成' );


