<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/basic/language/zh-tw.lang.php,  Wed 20/02/08 14:57:08 
  * Description : .
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => '編號' ,
   'LBL_DATE_ENTERED' => '建立日期' ,
   'LBL_DATE_MODIFIED' => '修改日期' ,
   'LBL_MODIFIED' => '修改者' ,
   'LBL_MODIFIED_ID' => '修改者編號' ,
   'LBL_MODIFIED_NAME' => '修改者' ,
   'LBL_CREATED' => '建立者' ,
   'LBL_CREATED_ID' => '建立者編號' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LBL_DELETED' => '刪除' ,
   'LBL_NAME' => '名稱' ,
   'LBL_CREATED_USER' => '由使用者建立' ,
   'LBL_MODIFIED_USER' => '由使用者修改' );


