<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Administration/language/zh-tw.lang.php, 20080506 Tue 06/05/08 22:59:58 
  * Description : 20080506.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '管理' ,
   'LBL_MODULE_TITLE' => '管理： 首頁' ,
   'LBL_NEW_FORM_TITLE' => '新增客戶' ,
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除客戶。' );


