<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/MergeRecords/language/zh-tw.lang.php, 20080502 Fri 02/05/08 22:46:02 
  * Description : 20080502.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => '合併資料' ,
   'LBL_MODULE_TITLE' => '合併資料：首頁' ,
   'LBL_SEARCH_FORM_TITLE' => '合併搜尋' ,
   'LBL_LIST_FORM_TITLE' => '合併列表' ,
   'LBL_LBL_MERGRE_RECORDS_STEP_1' => '步驟一：搜尋要合併的資料' ,
   'LBL_AVAIL_FIELDS' => '可用欄位' ,
   'LBL_FILTER_COND' => '過濾規則' ,
   'LBL_SELECTED_FIELDS' => '選擇的欄位' ,
   'LBL_MERGE_RECORDS_WITH' => '合併資料於' ,
   'LBL_MERGE_VALUE_OVER' => '合併數值超過' ,
   'LBL_NEXT_STEP_TITLE' => '移動到下一步[Ctrl+N]' ,
   'LBL_NEXT_STEP_BUTTON_KEY' => 'N' ,
   'LBL_NEXT_STEP_BUTTON_LABEL' => '下一步 >' ,
   'LBL_PERFORM_MERGE_BUTTON_TITLE' => '執行合併[Ctrl+P]' ,
   'LBL_PERFORM_MERGE_BUTTON_KEY' => 'P' ,
   'LBL_PERFORM_MERGE_BUTTON_LABEL' => '執行合併' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_TITLE' => '儲存合併[Ctrl+S]' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_KEY' => 'S' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_LABEL' => '儲存合併' ,
   'LBL_STEP2_FORM_TITLE' => '找到的可合併資料：' ,
   'LBL_SELECT_ERROR' => '在處理前您必須選擇。' ,
   'LBL_SELECT_PRIMARY' => '選擇合併的主要資料。' ,
   'LBL_CHANGE_PARENT' => '設定為主要' ,
   'LBL_REMOVE_FROM_MERGE' => '移除' ,
   'LBL_DIFF_COL_VALUES' => '主要資料列的欄位數值與合併的資料列有異：' ,
   'LBL_SAME_COL_VALUES' => '所有資料列的欄位數值相近：' ,
   'ERR_EXCEEDS_MAX' => '您現在可以一次合併最多五筆資料，超過的部份會自動忽略。' ,
   'LBL_DELETE_MESSAGE' => '這個操作將會刪除下面資料：' ,
   'LBL_PROCEED' => '確定？' );


