<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/issue/language/application/zh-tw.lang.php, 1 Tue 19/02/08 16:08:34 
  * Description : Taiwan PHP User Group | http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   '_priority_dom' => array (
      'P1' => '高' ,
      'P2' => 'Medium' ,
      'P3' => '低'   ),
   '_resolution_dom' => array (
      '' => '' ,
      'Accepted' => '已接受' ,
      'Duplicate' => '複製' ,
      'Closed' => '結束' ,
      'Out of Date' => '已過期' ,
      'Invalid' => '錯誤'   ),
   '_status_dom' => array (
      'New' => '新增' ,
      'Assigned' => '已指派' ,
      'Closed' => '結束' ,
      'Pending Input' => '處理中' ,
      'Rejected' => '已拒絕' ,
      'Duplicate' => '複製'   ),
   '_type_dom' => array (
      'Administration' => '管理' ,
      'Product' => '產品' ,
      'User' => '分配給：'   ));


