<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Notes/language/zh-tw.lang.php, 20080503 Sat 03/05/08 10:18:53 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除公司.' ,
   'LBL_ACCOUNT_ID' => '公司編號：' ,
   'LBL_CASE_ID' => '案件編號：' ,
   'LBL_CLOSE' => '關閉：' ,
   'LBL_COLON' => '：' ,
   'LBL_CONTACT_ID' => '聯絡人編號：' ,
   'LBL_CONTACT_NAME' => '聯絡人：' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '備註' ,
   'LBL_DESCRIPTION' => '說明' ,
   'LBL_EMAIL_ADDRESS' => '電子郵件地址：' ,
   'LBL_EMAIL_ATTACHMENT' => '郵件附加檔案' ,
   'LBL_FILE_MIME_TYPE' => 'Mime 類型' ,
   'LBL_FILE_URL' => '檔案網址' ,
   'LBL_FILENAME' => '附加檔案：' ,
   'LBL_LEAD_ID' => '準客戶編號：' ,
   'LBL_LIST_CONTACT_NAME' => '聯絡人' ,
   'LBL_LIST_DATE_MODIFIED' => '最新修改' ,
   'LBL_LIST_FILENAME' => '附加檔案' ,
   'LBL_LIST_FORM_TITLE' => '備註列表' ,
   'LBL_LIST_RELATED_TO' => '相關於' ,
   'LBL_LIST_SUBJECT' => '主旨' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_LIST_CONTACT' => '聯絡人' ,
   'LBL_MODULE_NAME' => '備註' ,
   'LBL_MODULE_TITLE' => '備註: 首頁' ,
   'LBL_NEW_FORM_TITLE' => '新增備註' ,
   'LBL_NOTE_STATUS' => '備註' ,
   'LBL_NOTE_SUBJECT' => '備註主題：' ,
   'LBL_NOTES_SUBPANEL_TITLE' => '附加檔案' ,
   'LBL_NOTE' => '備註：' ,
   'LBL_OPPORTUNITY_ID' => '機會編號：' ,
   'LBL_PARENT_ID' => '父編號：' ,
   'LBL_PARENT_TYPE' => '父類型：' ,
   'LBL_PHONE' => '電話：' ,
   'LBL_PORTAL_FLAG' => '在網站中顯示？' ,
   'LBL_EMBED_FLAG' => '附加在信中？' ,
   'LBL_PRODUCT_ID' => '產品編號：' ,
   'LBL_QUOTE_ID' => '報價單編號：' ,
   'LBL_RELATED_TO' => '相關：' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋備註' ,
   'LBL_STATUS' => '狀態' ,
   'LBL_SUBJECT' => '主旨：' ,
   'LNK_CALL_LIST' => '電話' ,
   'LNK_EMAIL_LIST' => '電子郵件' ,
   'LNK_IMPORT_NOTES' => '匯入記事' ,
   'LNK_MEETING_LIST' => '會議' ,
   'LNK_NEW_CALL' => '安排電話' ,
   'LNK_NEW_EMAIL' => '保留信件' ,
   'LNK_NEW_MEETING' => '安排會議' ,
   'LNK_NEW_NOTE' => '新增備註' ,
   'LNK_NEW_TASK' => '建立任務' ,
   'LNK_NOTE_LIST' => '備註' ,
   'LNK_TASK_LIST' => '任務' ,
   'LNK_VIEW_CALENDAR' => '今天' ,
   'LBL_MEMBER_OF' => '成員：' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => '指派的使用者' ,
   'LBL_REMOVING_ATTACHMENT' => '移除附加檔案' ,
   'ERR_REMOVING_ATTACHMENT' => '移除附加檔案時發生錯誤' ,
   'LBL_CREATED_BY' => '建立者' ,
   'LBL_MODIFIED_BY' => '修改者' ,
   'LBL_SEND_ANYWAYS' => '這封郵件沒有主旨，確定寄出/儲存？' );


