<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:58 **/


$Definition['%1$s on %2$s'] = '%1$s on %2$s';
$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';
$Definition['%s user(s) found.'] = '找到了 %s 個會員.';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '1 month after being sent';
$Definition['1 week after being sent'] = '1 week after being sent';

$Definition['2 weeks after being sent'] = '2 weeks after being sent';

$Definition['<General Error>'] = '<General Error>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Membership Approved';

$Definition['_Locale'] = '本地化';

$Definition['A url-friendly version of the category name for better SEO.'] = 'A url-friendly version of the category name for better SEO.';
$Definition['Action'] = '操作';
$Definition['Activate'] = '啟用';
$Definition['Add'] = '新增';
$Definition['Add Message'] = '新增公告資訊';
$Definition['Add Route'] = '新增路徑';
$Definition['Add User'] = '新增會員';
$Definition['Addons'] = '外掛';
$Definition['Administrator'] = '管理員';
$Definition['Advanced'] = '進階';
$Definition['Advanced Forum Settings'] = '進階討論區設定';
$Definition['All <span>16</span>'] = '所有 <span>16</span>';
$Definition['All <span>2</span>'] = '所有 <span>2</span>';
$Definition['Announce'] = '公告';
$Definition['Appearance'] = '外觀';
$Definition['Applicant'] = '申請者';
$Definition['Applicants'] = '申請者';
$Definition['Application'] = '應用程式';
$Definition['Application ID'] = '應用程式 ID';
$Definition['Application Secret'] = 'Application Secret';
$Definition['ApplicationHelp'] = 'Applications allow you to add large groups of functionality to your site.<br />Once an application has been added to your %s folder, you can enable or disable it here.';
$Definition['Applications'] = '應用程式';
$Definition['Approve'] = '同意';
$Definition['Archive Discussions'] = '討論歸檔';
$Definition['Are you sure you want to do that?'] = '你確定要這麼做?';
$Definition['at'] = 'at';
$Definition['Authentication'] = '認証';

$Definition['Banned'] = '封鎖';
$Definition['Banner'] = 'Banner';
$Definition['Banner Logo'] = 'Banner Logo';
$Definition['Banner Title'] = 'Banner 標題';

$Definition['Cancel'] = '取消';
$Definition['Capture locale pack changes.'] = 'Capture the changes between one of your locale packs and the Locale Developer. It will be put in the <code>changes.php</code> file.';
$Definition['Categories'] = '分類';
$Definition['Categories are used to help organize discussions. '] = '分類是用來協助組織討論區';
$Definition['Category'] = '分類';
$Definition['Category Url:'] = '分類 Url:';
$Definition['Change the way that new users register with the site.'] = 'Change the way that new users register with the site.';
$Definition['Check all permissions that apply for each role'] = 'Check all permissions that apply for each role';
$Definition['Check all roles that apply to this user:'] = 'Check all roles that apply to this user:';
$Definition['Choose a locale pack'] = '選擇一個語言';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Choose and configure your forum\'s authentication scheme.';
$Definition['Choose who can send out invitations to new members:'] = 'Choose who can send out invitations to new members:';
$Definition['Close'] = '關閉';
$Definition['comment(s)'] = '評論';
$Definition['Comments'] = '評論';
$Definition['Comments per Page'] = '每頁顯示評論數';
$Definition['Configure an Authenticator'] = 'Configure an Authenticator';
$Definition['Confirm'] = '確認';
$Definition['Confirm Email'] = '確認 Email';
$Definition['Consumer Key'] = 'Consumer Key';
$Definition['Consumer Secret'] = 'Consumer Secret';
$Definition['Conversation Messages'] = '對話訊息';
$Definition['Conversations'] = '對話';
$Definition['Copy'] = '複製';
$Definition['Copy locale pack.'] = 'Copy the definitions from a locale pack to the Locale Developer. The definitions will be put in the <code>copied.php</code> file.';
$Definition['Current Authenticator'] = 'Current Authenticator';
$Definition['Current Theme'] = '當前主題';
$Definition['Customize your Public Profile'] = 'Customize your Public Profile';

$Definition['Dashboard'] = '控制面板';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Decline'] = 'Decline';
$Definition['Delete'] = '刪除';
$Definition['Description'] = '描述';
$Definition['Disable'] = '停用';
$Definition['Disable Google Sign In'] = '停用 Google 登入';
$Definition['Disable OpenID'] = '停用 OpenID';
$Definition['Disabled <span>0</span>'] = '停用 <span>0</span>';
$Definition['Disabled <span>10</span>'] = '停用 <span>10</span>';
$Definition['Disabled <span>11</span>'] = '停用 <span>11</span>';
$Definition['Disabled <span>12</span>'] = '停用 <span>12</span>';
$Definition['Disabled <span>9</span>'] = '停用 <span>9</span>';
$Definition['Discussion & Comment Editing'] = '討論 & 評論編輯';
$Definition['discussion(s)'] = '討論';
$Definition['Discussions'] = '討論';
$Definition['Discussions per Page'] = '每頁顯示討論數';
$Definition['dot'] = 'dot';

$Definition['Edit'] = '編輯';
$Definition['edit'] = '編輯';
$Definition['Edit Category'] = '編輯分類';
$Definition['Edit User'] = '編輯會員';
$Definition['EditContentTimeout.Notes'] = 'Note: If a user is in a role that has permission to edit content, those permissions will override any value selected here.';
$Definition['Email'] = 'Email';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Email sent from the application will be addressed from the following name and address';
$Definition['Email visible to other users'] = 'Email visible to other users';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

	You have been approved for membership. Sign in now at the following link:

	  %2$s
	    
	  Have a great day！';
$Definition['Enable'] = '啟用';
$Definition['Enable Google Sign In'] = '啟用 Google 登入';
$Definition['Enable OpenID'] = '啟用 OpenID';
$Definition['Enabled <span>2</span>'] = '啟用 <span>2</span>';
$Definition['Enabled <span>4</span>'] = '啟用 <span>4</span>';
$Definition['Enabled <span>5</span>'] = '啟用 <span>5</span>';
$Definition['Enabled <span>6</span>'] = '啟用 <span>6</span>';
$Definition['Enabled <span>7</span>'] = '啟用 <span>7</span>';
$Definition['Existing members send invitations to new members.'] = 'Existing members send invitations to new members.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Facebook Settings'] = 'Facebook 設定';
$Definition['First Visit'] = '第一次訪問';
$Definition['For more help on localization check out the page <a href="%s">here</a>.'] = 'For more help on localization check out the page <a href="%s">here</a>.';
$Definition['Forum Settings'] = '討論區設定';

$Definition['Garden.Email.SupportAddress'] = 'Support email';
$Definition['Garden.Import.Description'] = 'Use this page to import data from another forum that was exported using Vanilla\'s exporter. For more information <a href="%s">see our importing documentation</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Import.Overwrite.Description'] = 'Warning: All data in this forum will be overwritten.';
$Definition['Generate'] = '產生';
$Definition['Generate Password'] = '產生密碼';
$Definition['Go'] = '衝';
$Definition['Google Sign In Settings'] = 'Google Sign In Settings';
$Definition['Guest'] = '訪客';

$Definition['here'] = 'here';

$Definition['Import'] = '匯入';
$Definition['Inbox'] = '收件匣';
$Definition['Information'] = '資訊';
$Definition['Internal'] = '內部';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['Invitations per month'] = '每月邀請數';
$Definition['Invitations will expire'] = '邀請過期';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.';

$Definition['Key Type'] = 'Key Type';
$Definition['Key Value'] = 'Key Value';

$Definition['Last Active'] = '最後活動';
$Definition['Last Visit'] = '最後訪問';
$Definition['Locale Developer'] = 'Locale Developer';
$Definition['Locale Developer Settings %s.'] = 'Locale Developer Settings %s.';
$Definition['Locale info file settings.'] = '<p>When you generate the zip file you can set the information for the locale below.</p> <p>You can download a zip of the locale pack by clicking <a href="%s">here</a>.</p>';
$Definition['Locale Key (Folder)'] = 'Locale Key (Folder)';
$Definition['Locale Name'] = '語言名稱';
$Definition['Locales'] = '語言';
$Definition['Locales are in your %s folder.'] = 'Locales allow you to support other languages on your site. Once an locale has been added to your %s folder, you can enable or disable it here.';
$Definition['Location'] = '位置';

$Definition['Manage Applicants'] = '管理申請人';
$Definition['Manage Applications'] = '管理應用程式';
$Definition['Manage Categories'] = '管理分類';
$Definition['Manage Messages'] = '管理公告資訊';
$Definition['Manage Plugins'] = '管理外掛';
$Definition['Manage Roles & Permissions'] = '管理角色 & 權限';
$Definition['Manage Routes'] = '管理路徑';
$Definition['Manage Spam'] = '管理垃圾資訊';
$Definition['Manage Themes'] = '管理主題';
$Definition['Manage Users'] = '管理會員';
$Definition['Manage your Plugins'] = '管理外掛';
$Definition['Max Comment Length'] = '評論最大長度';
$Definition['Member'] = '成員';
$Definition['Message'] = '公告資訊';
$Definition['Messages'] = '公告資訊';
$Definition['Messages can appear anywhere in your application.'] = 'Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.';
$Definition['Method'] = '方法';
$Definition['minute(s)'] = '分鐘';
$Definition['Moderator'] = '板主';

$Definition['Name'] = '名字';
$Definition['never'] = '絕不';
$Definition['New comments in the last day'] = '最近一天評論數';
$Definition['New comments in the last week'] = '最近一週評論數';
$Definition['New conversations in the last day'] = '最近一天對話數';
$Definition['New conversations in the last week'] = '最近一週對話數';
$Definition['New discussions in the last day'] = '最近一天討論數';
$Definition['New discussions in the last week'] = '最近一週討論數';
$Definition['New messages in the last day'] = '最近一天訊息數';
$Definition['New messages in the last week'] = '最近一週訊息數';
$Definition['New Password'] = '新密碼';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = '新會員必須經過管理員(也就是你)審閱';
$Definition['New users fill out a simple form and are granted access immediately.'] = '新會員在註冊後立即可以登入';
$Definition['New users in the last day'] = '最近一天新會員數';
$Definition['New users in the last week'] = '最近一週新會員數';
$Definition['None'] = '無';
$Definition['Not Authorized (401)'] = '沒有權限 (401)';
$Definition['Not Found (404)'] = '沒有找到 (404)';

$Definition['OK'] = 'OK';
$Definition['Okay'] = 'Okay';
$Definition['Only Allow Each User To Post'] = '只允許每個會員發送';
$Definition['OpenID Settings'] = 'OpenID 設定';
$Definition['Options'] = '選項';
$Definition['Or Spamblock For'] = '否則鎖定';
$Definition['Organize your Categories'] = '組織分類';
$Definition['Other Themes'] = '其他主題';
$Definition['Outgoing Email'] = '外送郵件';

$Definition['Page'] = '頁面';
$Definition['Panel Box'] = 'Panel Box';
$Definition['Password'] = '密碼';
$Definition['Password Options'] = '密碼選項';
$Definition['Permanent (301)'] = '永久移動 (301)';
$Definition['Please choose an authenticator to configure.'] = 'Please choose an authenticator to configure.';
$Definition['Plugin'] = '外掛';
$Definition['PluginHelp'] = 'Plugins allow you to add functionality to your site.<br />Once a plugin has been added to your %s folder, you can enable or disable it here.';
$Definition['Plugins'] = '外掛';
$Definition['Position'] = '位置';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.';
$Definition['Private Key'] = 'Private Key';
$Definition['Public Key'] = 'Public Key';

$Definition['Recently Active Users'] = '最近活動會員';
$Definition['Refresh Comments'] = '更新評論';
$Definition['Registration'] = '註冊';
$Definition['Remove'] = '刪除';
$Definition['Remove locale developer files.'] = 'Remove the locale deveoper files and reset your changes.';
$Definition['Requires: '] = '需求: ';
$Definition['Reset Password'] = '重置密碼';
$Definition['Reset password and send email notification to user'] = 'Reset password and send email notification to user';
$Definition['Reveal Password'] = '顯示密碼';
$Definition['Role'] = '角色';
$Definition['Roles & Permissions'] = '角色 & 權限';
$Definition['Roles determine user\'s permissions.'] = 'Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.';
$Definition['Route'] = '路徑';
$Definition['Route Expression'] = '路徑表達式';
$Definition['Routes'] = '路徑';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Routes can be used to redirect users to various parts of your site depending on the url.';

$Definition['Save'] = '儲存';
$Definition['Search'] = '搜尋';
$Definition['seconds'] = '秒';
$Definition['Select the file to import'] = 'Select the file to import';
$Definition['Settings'] = '設定';
$Definition['Sign Out'] = '登出';
$Definition['Sink'] = '下沉';
$Definition['SMTP Host'] = 'SMTP 主機';
$Definition['SMTP Password'] = 'SMTP 密碼';
$Definition['SMTP Port'] = 'SMTP 連接埠';
$Definition['SMTP Security'] = 'SMTP 安全';
$Definition['SMTP User'] = 'SMTP 會員';
$Definition['Spam'] = '垃圾資訊';
$Definition['Start your First Discussion'] = 'Start your First Discussion';

$Definition['Target'] = '目標';
$Definition['Temporary (302)'] = '臨時移動 (302)';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'The %s Authenticator does not have any custom configuration options.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'The addon could not be enabled because it generated a fatal error: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'The banner logo appears at the top of your forum.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.';
$Definition['The file failed to upload.'] = 'The file failed to upload.';
$Definition['ThemeHelp'] = 'Themes allow you to change the look &amp; feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Themes'] = '主題';
$Definition['There are currently no applicants.'] = 'There are currently no applicants.';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.';
$Definition['This plugin helps locale package development.'] = 'This plugin helps locale package development. The plugin keeps a working locale pack at <code>%s</code>.';
$Definition['Tools'] = 'Tools';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';
$Definition['Twitter Settings'] = 'Twitter 設定';
$Definition['Type'] = '類型';

$Definition['Unlimited'] = '無限制';
$Definition['Upload'] = '上傳';
$Definition['Url'] = 'Url';
$Definition['User'] = '會員';
$Definition['User Registration Settings'] = '會員註冊設定';
$Definition['Username'] = '帳號';
$Definition['Users'] = '會員';

$Definition['ValidateRequired'] = '%s 是必須的.';
$Definition['Vanilla.Archive.Description'] = 'You can choose to archive forum discussions older than a certain date. Archived discussions are effectively closed, allowing no new posts.';
$Definition['Version'] = '版本';
$Definition['Version %s'] = '版本 %s';
$Definition['version %s'] = '版本 %s';
$Definition['View'] = '察看';
$Definition['Visit Site'] = '訪問網站';

$Definition['Warning'] = '警告';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.';
$Definition['Welcome Aboard!'] = '歡迎加入！';
$Definition['What\'s the Buzz?'] = '最近動向';
$Definition['Within'] = 'Within';

$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'If you are ever locked out of your forum you can always log in using your original Vanilla email and password at <a href="%1$s">%1$s</a>';
$Definition['You can place files in your /uploads folder.'] = 'If your file is too
			large to upload directly to this page you can place it in your /uploads
					folder. Make sure the filename begins with the word <b>export</b> and ends
							with one of <b>.txt, .gz</b>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.';
$Definition['Your changes have been saved.'] = '你所做的改動已儲存.';
$Definition['Your settings have been saved.'] = '你的設定已儲存.';

// andelf added
$Definition['Media'] = '檔案';
