<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/templates/issue/language/application/zh-tw.lang.php, 1 Sat 01/03/08 17:30:27 
  * Description : http://twpug.net.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$app_list_strings = array ( 
   'Administration' => '管理' ,
   'Product' => '產品' ,
   'User' => '分配給：' ,
   'New' => 'New' ,
   'Assigned' => '已指派' ,
   'Closed' => '結束' ,
   'Pending Input' => '等待輸入' ,
   'Rejected' => '拒絕' ,
   'Duplicate' => '複製' ,
   'P1' => '高' ,
   'P2' => 'Medium' ,
   'P3' => '低' ,
   '' => '' ,
   'Accepted' => '已收到' ,
   'Duplicate' => '複製' ,
   'Closed' => '結束' ,
   'Out of Date' => '過期' ,
   'Invalid' => '錯誤' );


