<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: include/SugarObjects/implements/assignable/language/zh-tw.lang.php, 20080503 Sat 03/05/08 10:18:53 
  * Description : 20080503.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ASSIGNED_TO_ID' => '指派的使用者編號' ,
   'LBL_ASSIGNED_TO_NAME' => '指派給' );


