<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: /modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.zh-tw.lang.php, 20080423 Thu 24/04/08 00:08:47 
  * Description : 20080423.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');



