<?php

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Cases/language/zh-tw.lang.php, 20080502 Fri 02/05/08 22:46:02 
  * Description : 20080502.
  * Contributor(s): Finjon Kiang
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => '必須指定記錄編號才能刪除公司.' ,
   'LBL_ACCOUNT_ID' => '公司編號' ,
   'LBL_ACCOUNT_NAME' => '客戶名稱：' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => '待辦事項' ,
   'LBL_BUGS_SUBPANEL_TITLE' => '問題' ,
   'LBL_CASE_NUMBER' => '案件編號：' ,
   'LBL_CASE_SUBJECT' => '事件主題：' ,
   'LBL_CASE' => '案件：' ,
   'LBL_CONTACT_CASE_TITLE' => '案件聯絡人：' ,
   'LBL_CONTACT_NAME' => '聯絡人名稱：' ,
   'LBL_CONTACT_ROLE' => '角色：' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => '聯絡人' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => '案件' ,
   'LBL_DESCRIPTION' => '描述：' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => '紀錄' ,
   'LBL_INVITEE' => '聯絡人' ,
   'LBL_MEMBER_OF' => '公司' ,
   'LBL_MODULE_NAME' => '案件' ,
   'LBL_MODULE_TITLE' => '案件：首頁' ,
   'LBL_NEW_FORM_TITLE' => '新增案件' ,
   'LBL_NUMBER' => '數字：' ,
   'LBL_PRIORITY' => '優先順序：' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => '專案' ,
   'LBL_RESOLUTION' => '分析：' ,
   'LBL_SEARCH_FORM_TITLE' => '搜尋案件' ,
   'LBL_STATUS' => '狀態：' ,
   'LBL_SUBJECT' => '主旨：' ,
   'LBL_SYSTEM_ID' => '系統編號' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => '指派的使用者' ,
   'LBL_LIST_ACCOUNT_NAME' => '帳號' ,
   'LBL_LIST_ASSIGNED' => '指派給' ,
   'LBL_LIST_CLOSE' => '關閉' ,
   'LBL_LIST_FORM_TITLE' => '案件列表' ,
   'LBL_LIST_LAST_MODIFIED' => '最新修改' ,
   'LBL_LIST_MY_CASES' => '進行中的案件' ,
   'LBL_LIST_NUMBER' => '數字' ,
   'LBL_LIST_PRIORITY' => '優先' ,
   'LBL_LIST_STATUS' => '狀態' ,
   'LBL_LIST_SUBJECT' => '主旨' ,
   'LNK_CASE_LIST' => '案件' ,
   'LNK_NEW_CASE' => '建立案件' ,
   'NTC_REMOVE_FROM_BUG_CONFIRMATION' => '您確定要從問題中移除這個案件？' ,
   'NTC_REMOVE_INVITEE' => '您確定要從案件中移除這個聯絡人？' ,
   'LBL_LIST_DATE_CREATED' => '建立日期' ,
   'LBL_ASSIGNED_TO_NAME' => '指派給' ,
   'LBL_TYPE' => '類型' ,
   'LBL_WORK_LOG' => '作業記錄' );


